codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    patch:
      foundation-domain:
        target: 80%
        threshold: 0%
        paths:
          - "backend/modules/foundation/domain/"
        informational: false
      prompt-domain:
        target: 80%
        threshold: 0%
        paths:
          - "backend/modules/prompt/domain/"
        informational: false
      evaluation-domain:
        target: 80%
        threshold: 0%
        paths:
          - "backend/modules/evaluation/domain/"
        informational: false
      llm-domain:
        target: 80%
        threshold: 0%
        paths:
          - "backend/modules/llm/domain/"
        informational: false
      observability-domain:
        target: 80%
        threshold: 0%
        paths:
          - "backend/modules/observability/domain/"
        informational: false
      default:
        target: 80%
        threshold: 0%
        paths:
          - "backend/"
        informational: false

ignore:
  - "**/mocks/**"
  - "**/gorm_gen/**"
  - "**/kitex_gen/**"
  - "**/loop_gen/**"
  - "**/wire.go"
  - "**/wire_gen.go"
  - "**/errno/**"
  - "**/main.go"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no