version: "2"

run:
  timeout: 5m
  skip-dirs:
    - kitex_gen
    - loop_gen
    - gorm_gen

linters: # https://golangci-lint.run/usage/linters/
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unconvert

formatters:
  enable:
    - goimports
    - gofmt
    - gofumpt

# Refer to https://golangci-lint.run/usage/linters
linters-settings:
  gofumpt:
    # Choose whether to use the extra rules.
    extra-rules: true
  goimports: