run:
  timeout: 10m
  # 使用 issues.exclude-dirs 替代废弃的 skip-dirs
  go: "1.21"

# 排除目录配置
issues:
  exclude-dirs:
    - kitex_gen
    - loop_gen
    - gorm_gen
  exclude-rules:
    - path: "coze/loop/apis/middleware.go"
      linters:
        - unused
  # 设置默认严重级别
  severity-rules:
    - linters:
        - unconvert
        - unused
      severity: warning
    - linters:
        - govet
        - ineffassign
        - staticcheck
      severity: error

linters: # https://golangci-lint.run/usage/linters/
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unconvert
    - gofmt
    - goimports
    - gofumpt

# Refer to https://golangci-lint.run/usage/linters
linters-settings:
  gofumpt:
    # Choose whether to use the extra rules.
    extra-rules: true
  goimports:
    local-prefixes: "github.com/coze-dev/coze-loop"
  govet:
    enable-all: true
    disable:
      - fieldalignment