run:
  timeout: 5m
  skip-dirs:
    - kitex_gen
    - loop_gen
    - gorm_gen

linters: # https://golangci-lint.run/usage/linters/
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unconvert
    - goimports
    - gofmt
    - gofumpt

# Refer to https://golangci-lint.run/usage/linters
linters-settings:
  gofumpt:
    # Choose whether to use the extra rules.
    extra-rules: true
  goimports:
    local-prefixes: github.com/coze-dev/cozeloop
  typecheck:
    # 排除特定的包导入错误
    skip-packages:
      - "github.com/coze-dev/cozeloop-go"