header:
  license:
    spdx-id: Apache-2.0
    pattern: |
      Copyright (c) \d{4} Bytedance Ltd. and/or its affiliates
      SPDX-License-Identifier: Apache-2.0

  paths:
    - '**/*.go'
    - frontend/apps/**/*.{ts,tsx,less,css}
    - frontend/packages/cozeloop/**/*.{ts,tsx,less,css}

  paths-ignore:
    - 'node_modules'
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - '**/*.hz'
    - '**/*.yaml'
    - 'LICENSE'
    - 'NOTICE'
    - "**/mocks/**"
    - "**/gorm_gen/**"
    - "**/kitex_gen/**"
    - "**/loop_gen/**"
    - "**/wire_gen.go"
    - "**/errno/**"
    - "backend/script/cloudwego/tmpl/streaming.go"
    - "backend/api/router/register.go"
    - "backend/api/router/coze/loop/apis/coze.loop.apis.go"
    - "backend/modules/observability/domain/trace/entity/collector/**/*.go"
    - "backend/modules/observability/domain/trace/service/collector/processor/queueprocessor/queue_processor.go"
    - 'frontend/packages/cozeloop/api-schema/src/api/idl'

  comment: on-failure

dependency:
  files:
    - ../backend/go.mod
  allowed-licenses:
    - Apache-2.0
    - MIT
    - BSD-2-Clause
    - BSD-3-Clause
    - ISC
    - Unlicense
    - CC0-1.0
    - WTFPL
    - MPL-2.0
  license-mapping:
    github.com/cloudwego/eino-ext/components/model/ark: Apache-2.0
    github.com/cloudwego/eino-ext/components/model/arkbot: Apache-2.0
    github.com/cloudwego/eino-ext/components/model/claude: Apache-2.0
    github.com/cloudwego/eino-ext/components/model/deepseek: Apache-2.0
    github.com/cloudwego/eino-ext/components/model/gemini: Apache-2.0
    github.com/cloudwego/eino-ext/components/model/ollama: Apache-2.0
    github.com/cloudwego/eino-ext/components/model/openai: Apache-2.0
    github.com/cloudwego/eino-ext/components/model/qianfan: Apache-2.0
    github.com/cloudwego/eino-ext/components/model/qwen: Apache-2.0
    github.com/cloudwego/eino-ext/libs/acl/openai: Apache-2.0
  