// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	metric "github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability/metric"
)

// GetMetrics .
// @router /api/observability/v1/metrics/list [POST]
func GetMetrics(ctx context.Context, c *app.RequestContext) {
	var err error
	var req metric.GetMetricsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(metric.GetMetricsResponse)

	c.JSON(consts.StatusOK, resp)
}
