// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/apis/observabilitymetricservice"
)

var observabilityMetricClient observabilitymetricservice.Client

// GetMetrics .
// @router /api/observability/v1/metrics/list [POST]
func GetMetrics(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityMetricClient.GetMetrics)
}
