apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-faas.fullname" . }}-bootstrap-configmap
  labels:
    {{- include "python-faas.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
{{ .Files.Get "bootstrap/entrypoint.sh" | indent 4 }}
  healthcheck.sh: |
{{ .Files.Get "bootstrap/healthcheck.sh" | indent 4 }}
  pyodide_faas_server.ts: |
{{ .Files.Get "bootstrap/pyodide_faas_server.ts" | indent 4 }}
  pyodide_pool_manager.ts: |
{{ .Files.Get "bootstrap/pyodide_pool_manager.ts" | indent 4 }}
  deno.json: |
{{ .Files.Get "bootstrap/deno.json" | indent 4 }}