apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.name" . }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "application.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "application.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ (.Values.custom.image.pullSecrets | default .Values.image.pullSecrets) | quote }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      volumes:
        - name: bootstrap
          configMap:
            name: {{ include "configmap.name" . }}
      containers:
        - name: {{ include "application.name" . }}
          image: {{ include "image.fullname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: bootstrap
              mountPath: {{ include "bootstrap.path" . }}
              readOnly: true
          env:
            - name: DENO_DIR
              value: {{ .Values.env.deno.dir | quote }}
            - name: DENO_NO_UPDATE_CHECK
              value: {{ .Values.env.deno.noUpdateCheck | quote }}
            - name: DENO_V8_FLAGS
              value: {{ .Values.env.deno.v8Flags | quote }}
            - name: FAAS_WORKSPACE
              value: {{ .Values.env.faas.workspace | quote }}
            - name: FAAS_PORT
              value: {{ .Values.env.faas.port | quote }}
            - name: FAAS_TIMEOUT
              value: {{ .Values.env.faas.timeout | quote }}
            - name: FAAS_LANGUAGE
              value: {{ .Values.env.faas.language | quote }}
          command: [ "/bin/sh" ]
          args: [ {{ include "entrypoint.path" . | quote }} ]
          resources:
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu | quote }}
              memory: {{ .Values.deployment.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu | quote }}
              memory: {{ .Values.deployment.resources.requests.memory | quote }}
          livenessProbe:
            exec:
              command: [ "/bin/sh", {{ include "healthcheck.path" . | quote }} ]
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 20
            failureThreshold: 20

