// Code generated by cozeloop. DO NOT EDIT.
package loopenapi // import github.com/coze-dev/coze-loop/backend/loopenapi

import (
	"context"

	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/endpoint"
	"github.com/cloudwego/kitex/pkg/rpcinfo"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/prompt/openapi"
)

type LocalPromptOpenAPIService struct {
	impl openapi.PromptOpenAPIService // the service implementation
	mds  endpoint.Middleware
}

func NewLocalPromptOpenAPIService(impl openapi.PromptOpenAPIService, mds ...endpoint.Middleware) *LocalPromptOpenAPIService {
	return &LocalPromptOpenAPIService{
		impl: impl,
		mds:  endpoint.Chain(mds...),
	}
}

func (l *LocalPromptOpenAPIService) BatchGetPromptByPromptKey(ctx context.Context, req *openapi.BatchGetPromptByPromptKeyRequest, callOptions ...callopt.Option) (*openapi.BatchGetPromptByPromptKeyResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*openapi.PromptOpenAPIServiceBatchGetPromptByPromptKeyArgs)
		result := out.(*openapi.PromptOpenAPIServiceBatchGetPromptByPromptKeyResult)
		resp, err := l.impl.BatchGetPromptByPromptKey(ctx, arg.Req)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &openapi.PromptOpenAPIServiceBatchGetPromptByPromptKeyArgs{Req: req}
	result := &openapi.PromptOpenAPIServiceBatchGetPromptByPromptKeyResult{}
	ctx = l.injectRPCInfo(ctx, "BatchGetPromptByPromptKey")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

// ValidateTemplate 验证Jinja2模板语法
func (l *LocalPromptOpenAPIService) ValidateTemplate(ctx context.Context, req *openapi.ValidateTemplateRequest, callOptions ...callopt.Option) (*openapi.ValidateTemplateResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*openapi.PromptOpenAPIServiceValidateTemplateArgs)
		result := out.(*openapi.PromptOpenAPIServiceValidateTemplateResult)
		resp, err := l.impl.ValidateTemplate(ctx, arg.Req)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &openapi.PromptOpenAPIServiceValidateTemplateArgs{Req: req}
	result := &openapi.PromptOpenAPIServiceValidateTemplateResult{}
	ctx = l.injectRPCInfo(ctx, "ValidateTemplate")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

// PreviewTemplate 预览Jinja2模板渲染结果
func (l *LocalPromptOpenAPIService) PreviewTemplate(ctx context.Context, req *openapi.PreviewTemplateRequest, callOptions ...callopt.Option) (*openapi.PreviewTemplateResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*openapi.PromptOpenAPIServicePreviewTemplateArgs)
		result := out.(*openapi.PromptOpenAPIServicePreviewTemplateResult)
		resp, err := l.impl.PreviewTemplate(ctx, arg.Req)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &openapi.PromptOpenAPIServicePreviewTemplateArgs{Req: req}
	result := &openapi.PromptOpenAPIServicePreviewTemplateResult{}
	ctx = l.injectRPCInfo(ctx, "PreviewTemplate")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

func (l *LocalPromptOpenAPIService) injectRPCInfo(ctx context.Context, method string) context.Context {
	rpcStats := rpcinfo.AsMutableRPCStats(rpcinfo.NewRPCStats())
	ri := rpcinfo.NewRPCInfo(
		rpcinfo.NewEndpointInfo("PromptOpenAPIService", method, nil, nil),
		rpcinfo.NewEndpointInfo("PromptOpenAPIService", method, nil, nil),
		rpcinfo.NewServerInvocation(),
		nil,
		rpcStats.ImmutableView(),
	)
	return rpcinfo.NewCtxWithRPCInfo(ctx, ri)
}
