services:
  app:
    build:
      context: ../../..
      dockerfile: ./release/image/debug.Dockerfile
    image: "coze-dev/coze-loop:debug"
    ports:
      - "${COZE_LOOP_APP_DEBUG_PORT}:40000"
    entrypoint: [ "sh", "/coze-loop/bootstrap/entrypoint.sh" ]