// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/domain/repo (interfaces: ILabelRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/entity"
	repo "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockILabelRepo is a mock of ILabelRepo interface.
type MockILabelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockILabelRepoMockRecorder
}

// MockILabelRepoMockRecorder is the mock recorder for MockILabelRepo.
type MockILabelRepoMockRecorder struct {
	mock *MockILabelRepo
}

// NewMockILabelRepo creates a new mock instance.
func NewMockILabelRepo(ctrl *gomock.Controller) *MockILabelRepo {
	mock := &MockILabelRepo{ctrl: ctrl}
	mock.recorder = &MockILabelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILabelRepo) EXPECT() *MockILabelRepoMockRecorder {
	return m.recorder
}

// BatchGetLabel mocks base method.
func (m *MockILabelRepo) BatchGetLabel(arg0 context.Context, arg1 int64, arg2 []string) ([]*entity.PromptLabel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetLabel", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*entity.PromptLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetLabel indicates an expected call of BatchGetLabel.
func (mr *MockILabelRepoMockRecorder) BatchGetLabel(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetLabel", reflect.TypeOf((*MockILabelRepo)(nil).BatchGetLabel), arg0, arg1, arg2)
}

// BatchGetPromptVersionByLabel mocks base method.
func (m *MockILabelRepo) BatchGetPromptVersionByLabel(arg0 context.Context, arg1 []repo.PromptLabelQuery, arg2 ...repo.GetLabelMappingOptionFunc) (map[repo.PromptLabelQuery]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGetPromptVersionByLabel", varargs...)
	ret0, _ := ret[0].(map[repo.PromptLabelQuery]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetPromptVersionByLabel indicates an expected call of BatchGetPromptVersionByLabel.
func (mr *MockILabelRepoMockRecorder) BatchGetPromptVersionByLabel(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetPromptVersionByLabel", reflect.TypeOf((*MockILabelRepo)(nil).BatchGetPromptVersionByLabel), varargs...)
}

// CreateLabel mocks base method.
func (m *MockILabelRepo) CreateLabel(arg0 context.Context, arg1 *entity.PromptLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockILabelRepoMockRecorder) CreateLabel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockILabelRepo)(nil).CreateLabel), arg0, arg1)
}

// GetCommitLabels mocks base method.
func (m *MockILabelRepo) GetCommitLabels(arg0 context.Context, arg1 int64, arg2 []string) (map[string][]*entity.PromptLabel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitLabels", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string][]*entity.PromptLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitLabels indicates an expected call of GetCommitLabels.
func (mr *MockILabelRepoMockRecorder) GetCommitLabels(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitLabels", reflect.TypeOf((*MockILabelRepo)(nil).GetCommitLabels), arg0, arg1, arg2)
}

// ListLabel mocks base method.
func (m *MockILabelRepo) ListLabel(arg0 context.Context, arg1 repo.ListLabelParam) ([]*entity.PromptLabel, *int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabel", arg0, arg1)
	ret0, _ := ret[0].([]*entity.PromptLabel)
	ret1, _ := ret[1].(*int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLabel indicates an expected call of ListLabel.
func (mr *MockILabelRepoMockRecorder) ListLabel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabel", reflect.TypeOf((*MockILabelRepo)(nil).ListLabel), arg0, arg1)
}

// UpdateCommitLabels mocks base method.
func (m *MockILabelRepo) UpdateCommitLabels(arg0 context.Context, arg1 repo.UpdateCommitLabelsParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommitLabels", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommitLabels indicates an expected call of UpdateCommitLabels.
func (mr *MockILabelRepoMockRecorder) UpdateCommitLabels(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommitLabels", reflect.TypeOf((*MockILabelRepo)(nil).UpdateCommitLabels), arg0, arg1)
}
