// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/domain/repo (interfaces: IManageRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/entity"
	repo "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockIManageRepo is a mock of IManageRepo interface.
type MockIManageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIManageRepoMockRecorder
}

// MockIManageRepoMockRecorder is the mock recorder for MockIManageRepo.
type MockIManageRepoMockRecorder struct {
	mock *MockIManageRepo
}

// NewMockIManageRepo creates a new mock instance.
func NewMockIManageRepo(ctrl *gomock.Controller) *MockIManageRepo {
	mock := &MockIManageRepo{ctrl: ctrl}
	mock.recorder = &MockIManageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIManageRepo) EXPECT() *MockIManageRepoMockRecorder {
	return m.recorder
}

// CommitDraft mocks base method.
func (m *MockIManageRepo) CommitDraft(arg0 context.Context, arg1 repo.CommitDraftParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitDraft", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitDraft indicates an expected call of CommitDraft.
func (mr *MockIManageRepoMockRecorder) CommitDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitDraft", reflect.TypeOf((*MockIManageRepo)(nil).CommitDraft), arg0, arg1)
}

// CreatePrompt mocks base method.
func (m *MockIManageRepo) CreatePrompt(arg0 context.Context, arg1 *entity.Prompt) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrompt", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrompt indicates an expected call of CreatePrompt.
func (mr *MockIManageRepoMockRecorder) CreatePrompt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrompt", reflect.TypeOf((*MockIManageRepo)(nil).CreatePrompt), arg0, arg1)
}

// DeletePrompt mocks base method.
func (m *MockIManageRepo) DeletePrompt(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrompt", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrompt indicates an expected call of DeletePrompt.
func (mr *MockIManageRepoMockRecorder) DeletePrompt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrompt", reflect.TypeOf((*MockIManageRepo)(nil).DeletePrompt), arg0, arg1)
}

// GetPrompt mocks base method.
func (m *MockIManageRepo) GetPrompt(arg0 context.Context, arg1 repo.GetPromptParam) (*entity.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrompt", arg0, arg1)
	ret0, _ := ret[0].(*entity.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrompt indicates an expected call of GetPrompt.
func (mr *MockIManageRepoMockRecorder) GetPrompt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrompt", reflect.TypeOf((*MockIManageRepo)(nil).GetPrompt), arg0, arg1)
}

// ListCommitInfo mocks base method.
func (m *MockIManageRepo) ListCommitInfo(arg0 context.Context, arg1 repo.ListCommitInfoParam) (*repo.ListCommitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommitInfo", arg0, arg1)
	ret0, _ := ret[0].(*repo.ListCommitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommitInfo indicates an expected call of ListCommitInfo.
func (mr *MockIManageRepoMockRecorder) ListCommitInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommitInfo", reflect.TypeOf((*MockIManageRepo)(nil).ListCommitInfo), arg0, arg1)
}

// ListParentPrompt mocks base method.
func (m *MockIManageRepo) ListParentPrompt(arg0 context.Context, arg1 repo.ListParentPromptParam) (map[string][]*repo.PromptCommitVersions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParentPrompt", arg0, arg1)
	ret0, _ := ret[0].(map[string][]*repo.PromptCommitVersions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParentPrompt indicates an expected call of ListParentPrompt.
func (mr *MockIManageRepoMockRecorder) ListParentPrompt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParentPrompt", reflect.TypeOf((*MockIManageRepo)(nil).ListParentPrompt), arg0, arg1)
}

// ListPrompt mocks base method.
func (m *MockIManageRepo) ListPrompt(arg0 context.Context, arg1 repo.ListPromptParam) (*repo.ListPromptResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrompt", arg0, arg1)
	ret0, _ := ret[0].(*repo.ListPromptResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrompt indicates an expected call of ListPrompt.
func (mr *MockIManageRepoMockRecorder) ListPrompt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrompt", reflect.TypeOf((*MockIManageRepo)(nil).ListPrompt), arg0, arg1)
}

// MGetPrompt mocks base method.
func (m *MockIManageRepo) MGetPrompt(arg0 context.Context, arg1 []repo.GetPromptParam, arg2 ...repo.GetPromptOptionFunc) (map[repo.GetPromptParam]*entity.Prompt, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGetPrompt", varargs...)
	ret0, _ := ret[0].(map[repo.GetPromptParam]*entity.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGetPrompt indicates an expected call of MGetPrompt.
func (mr *MockIManageRepoMockRecorder) MGetPrompt(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGetPrompt", reflect.TypeOf((*MockIManageRepo)(nil).MGetPrompt), varargs...)
}

// MGetPromptBasicByPromptKey mocks base method.
func (m *MockIManageRepo) MGetPromptBasicByPromptKey(arg0 context.Context, arg1 int64, arg2 []string, arg3 ...repo.GetPromptBasicOptionFunc) ([]*entity.Prompt, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGetPromptBasicByPromptKey", varargs...)
	ret0, _ := ret[0].([]*entity.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGetPromptBasicByPromptKey indicates an expected call of MGetPromptBasicByPromptKey.
func (mr *MockIManageRepoMockRecorder) MGetPromptBasicByPromptKey(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGetPromptBasicByPromptKey", reflect.TypeOf((*MockIManageRepo)(nil).MGetPromptBasicByPromptKey), varargs...)
}

// MGetVersionsByPromptID mocks base method.
func (m *MockIManageRepo) MGetVersionsByPromptID(arg0 context.Context, arg1 int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MGetVersionsByPromptID", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGetVersionsByPromptID indicates an expected call of MGetVersionsByPromptID.
func (mr *MockIManageRepoMockRecorder) MGetVersionsByPromptID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGetVersionsByPromptID", reflect.TypeOf((*MockIManageRepo)(nil).MGetVersionsByPromptID), arg0, arg1)
}

// SaveDraft mocks base method.
func (m *MockIManageRepo) SaveDraft(arg0 context.Context, arg1 *entity.Prompt) (*entity.DraftInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDraft", arg0, arg1)
	ret0, _ := ret[0].(*entity.DraftInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveDraft indicates an expected call of SaveDraft.
func (mr *MockIManageRepoMockRecorder) SaveDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDraft", reflect.TypeOf((*MockIManageRepo)(nil).SaveDraft), arg0, arg1)
}

// UpdatePrompt mocks base method.
func (m *MockIManageRepo) UpdatePrompt(arg0 context.Context, arg1 repo.UpdatePromptParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrompt", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrompt indicates an expected call of UpdatePrompt.
func (mr *MockIManageRepoMockRecorder) UpdatePrompt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrompt", reflect.TypeOf((*MockIManageRepo)(nil).UpdatePrompt), arg0, arg1)
}
