// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/domain/repo (interfaces: IToolRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/entity"
	repo "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockIToolRepo is a mock of IToolRepo interface.
type MockIToolRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIToolRepoMockRecorder
}

// MockIToolRepoMockRecorder is the mock recorder for MockIToolRepo.
type MockIToolRepoMockRecorder struct {
	mock *MockIToolRepo
}

// NewMockIToolRepo creates a new mock instance.
func NewMockIToolRepo(ctrl *gomock.Controller) *MockIToolRepo {
	mock := &MockIToolRepo{ctrl: ctrl}
	mock.recorder = &MockIToolRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToolRepo) EXPECT() *MockIToolRepoMockRecorder {
	return m.recorder
}

// CommitDraft mocks base method.
func (m *MockIToolRepo) CommitDraft(arg0 context.Context, arg1 repo.CommitToolDraftParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitDraft", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitDraft indicates an expected call of CommitDraft.
func (mr *MockIToolRepoMockRecorder) CommitDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitDraft", reflect.TypeOf((*MockIToolRepo)(nil).CommitDraft), arg0, arg1)
}

// CreateTool mocks base method.
func (m *MockIToolRepo) CreateTool(arg0 context.Context, arg1 *entity.CommonTool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTool", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTool indicates an expected call of CreateTool.
func (mr *MockIToolRepoMockRecorder) CreateTool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTool", reflect.TypeOf((*MockIToolRepo)(nil).CreateTool), arg0, arg1)
}

// GetTool mocks base method.
func (m *MockIToolRepo) GetTool(arg0 context.Context, arg1 repo.GetToolParam) (*entity.CommonTool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTool", arg0, arg1)
	ret0, _ := ret[0].(*entity.CommonTool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTool indicates an expected call of GetTool.
func (mr *MockIToolRepoMockRecorder) GetTool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTool", reflect.TypeOf((*MockIToolRepo)(nil).GetTool), arg0, arg1)
}

// ListTool mocks base method.
func (m *MockIToolRepo) ListTool(arg0 context.Context, arg1 repo.ListToolParam) (*repo.ListToolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTool", arg0, arg1)
	ret0, _ := ret[0].(*repo.ListToolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTool indicates an expected call of ListTool.
func (mr *MockIToolRepoMockRecorder) ListTool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTool", reflect.TypeOf((*MockIToolRepo)(nil).ListTool), arg0, arg1)
}

// ListToolCommitInfo mocks base method.
func (m *MockIToolRepo) ListToolCommitInfo(arg0 context.Context, arg1 repo.ListToolCommitParam) (*repo.ListToolCommitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListToolCommitInfo", arg0, arg1)
	ret0, _ := ret[0].(*repo.ListToolCommitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListToolCommitInfo indicates an expected call of ListToolCommitInfo.
func (mr *MockIToolRepoMockRecorder) ListToolCommitInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListToolCommitInfo", reflect.TypeOf((*MockIToolRepo)(nil).ListToolCommitInfo), arg0, arg1)
}

// MGetTool mocks base method.
func (m *MockIToolRepo) MGetTool(arg0 context.Context, arg1 []repo.MGetToolQuery) (map[repo.MGetToolQuery]*entity.CommonTool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MGetTool", arg0, arg1)
	ret0, _ := ret[0].(map[repo.MGetToolQuery]*entity.CommonTool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGetTool indicates an expected call of MGetTool.
func (mr *MockIToolRepoMockRecorder) MGetTool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGetTool", reflect.TypeOf((*MockIToolRepo)(nil).MGetTool), arg0, arg1)
}

// SaveDraft mocks base method.
func (m *MockIToolRepo) SaveDraft(arg0 context.Context, arg1 *entity.CommonTool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDraft", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDraft indicates an expected call of SaveDraft.
func (mr *MockIToolRepoMockRecorder) SaveDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDraft", reflect.TypeOf((*MockIToolRepo)(nil).SaveDraft), arg0, arg1)
}
