// Code generated by cozeloop. DO NOT EDIT.
package lomanage // import github.com/coze-dev/coze-loop/backend/lomanage

import (
	"context"

	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/endpoint"
	"github.com/cloudwego/kitex/pkg/rpcinfo"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/prompt/tool/manage"
)

type LocalToolManageService struct {
	impl manage.ToolManageService // the service implementation
	mds  endpoint.Middleware
}

func NewLocalToolManageService(impl manage.ToolManageService, mds ...endpoint.Middleware) *LocalToolManageService {
	return &LocalToolManageService{
		impl: impl,
		mds:  endpoint.Chain(mds...),
	}
}

func (l *LocalToolManageService) CreateTool(ctx context.Context, request *manage.CreateToolRequest, callOptions ...callopt.Option) (*manage.CreateToolResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*manage.ToolManageServiceCreateToolArgs)
		result := out.(*manage.ToolManageServiceCreateToolResult)
		resp, err := l.impl.CreateTool(ctx, arg.Request)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &manage.ToolManageServiceCreateToolArgs{Request: request}
	result := &manage.ToolManageServiceCreateToolResult{}
	ctx = l.injectRPCInfo(ctx, "CreateTool")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

func (l *LocalToolManageService) GetToolDetail(ctx context.Context, request *manage.GetToolDetailRequest, callOptions ...callopt.Option) (*manage.GetToolDetailResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*manage.ToolManageServiceGetToolDetailArgs)
		result := out.(*manage.ToolManageServiceGetToolDetailResult)
		resp, err := l.impl.GetToolDetail(ctx, arg.Request)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &manage.ToolManageServiceGetToolDetailArgs{Request: request}
	result := &manage.ToolManageServiceGetToolDetailResult{}
	ctx = l.injectRPCInfo(ctx, "GetToolDetail")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

func (l *LocalToolManageService) ListTool(ctx context.Context, request *manage.ListToolRequest, callOptions ...callopt.Option) (*manage.ListToolResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*manage.ToolManageServiceListToolArgs)
		result := out.(*manage.ToolManageServiceListToolResult)
		resp, err := l.impl.ListTool(ctx, arg.Request)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &manage.ToolManageServiceListToolArgs{Request: request}
	result := &manage.ToolManageServiceListToolResult{}
	ctx = l.injectRPCInfo(ctx, "ListTool")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

func (l *LocalToolManageService) SaveToolDetail(ctx context.Context, request *manage.SaveToolDetailRequest, callOptions ...callopt.Option) (*manage.SaveToolDetailResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*manage.ToolManageServiceSaveToolDetailArgs)
		result := out.(*manage.ToolManageServiceSaveToolDetailResult)
		resp, err := l.impl.SaveToolDetail(ctx, arg.Request)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &manage.ToolManageServiceSaveToolDetailArgs{Request: request}
	result := &manage.ToolManageServiceSaveToolDetailResult{}
	ctx = l.injectRPCInfo(ctx, "SaveToolDetail")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

func (l *LocalToolManageService) CommitToolDraft(ctx context.Context, request *manage.CommitToolDraftRequest, callOptions ...callopt.Option) (*manage.CommitToolDraftResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*manage.ToolManageServiceCommitToolDraftArgs)
		result := out.(*manage.ToolManageServiceCommitToolDraftResult)
		resp, err := l.impl.CommitToolDraft(ctx, arg.Request)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &manage.ToolManageServiceCommitToolDraftArgs{Request: request}
	result := &manage.ToolManageServiceCommitToolDraftResult{}
	ctx = l.injectRPCInfo(ctx, "CommitToolDraft")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

func (l *LocalToolManageService) ListToolCommit(ctx context.Context, request *manage.ListToolCommitRequest, callOptions ...callopt.Option) (*manage.ListToolCommitResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*manage.ToolManageServiceListToolCommitArgs)
		result := out.(*manage.ToolManageServiceListToolCommitResult)
		resp, err := l.impl.ListToolCommit(ctx, arg.Request)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &manage.ToolManageServiceListToolCommitArgs{Request: request}
	result := &manage.ToolManageServiceListToolCommitResult{}
	ctx = l.injectRPCInfo(ctx, "ListToolCommit")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

func (l *LocalToolManageService) BatchGetTools(ctx context.Context, request *manage.BatchGetToolsRequest, callOptions ...callopt.Option) (*manage.BatchGetToolsResponse, error) {
	chain := l.mds(func(ctx context.Context, in, out interface{}) error {
		arg := in.(*manage.ToolManageServiceBatchGetToolsArgs)
		result := out.(*manage.ToolManageServiceBatchGetToolsResult)
		resp, err := l.impl.BatchGetTools(ctx, arg.Request)
		if err != nil {
			return err
		}
		result.SetSuccess(resp)
		return nil
	})

	arg := &manage.ToolManageServiceBatchGetToolsArgs{Request: request}
	result := &manage.ToolManageServiceBatchGetToolsResult{}
	ctx = l.injectRPCInfo(ctx, "BatchGetTools")
	if err := chain(ctx, arg, result); err != nil {
		return nil, err
	}
	return result.GetSuccess(), nil
}

func (l *LocalToolManageService) injectRPCInfo(ctx context.Context, method string) context.Context {
	rpcStats := rpcinfo.AsMutableRPCStats(rpcinfo.NewRPCStats())
	ri := rpcinfo.NewRPCInfo(
		rpcinfo.NewEndpointInfo("ToolManageService", method, nil, nil),
		rpcinfo.NewEndpointInfo("ToolManageService", method, nil, nil),
		rpcinfo.NewServerInvocation(),
		nil,
		rpcStats.ImmutableView(),
	)
	return rpcinfo.NewCtxWithRPCInfo(ctx, ri)
}
