# 基础服务：全部使用基础镜像

ingress:
  host: open.coze-loop.minikube
  type: nginx
  className: nginx

custom: &custom
  image:
    registry: "docker.io"
    tag: "new"
    repository: "coze-dev/coze-loop"
  redis:
    disabled: true
  mysql:
    disabled: true
  clickhouse:
    disabled: true
  oss:
    disabled: true
  rmq:
    disabled: true

# 固定，不要动，用于传递全局变量
coze-loop-app:
  custom: *custom
coze-loop-nginx:
  custom: *custom
coze-loop-redis:
  custom: *custom
coze-loop-mysql:
  custom: *custom
coze-loop-clickhouse:
  custom: *custom
coze-loop-minio:
  custom: *custom
coze-loop-rmq-namesrv:
  custom: *custom
coze-loop-rmq-broker:
  custom: *custom
coze-loop-python-faas:
  custom: *custom
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 5
    readiness:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 15
      timeoutSeconds: 10
      failureThreshold: 5
coze-loop-js-faas:
  custom: *custom