service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

image:
  registry: "docker.io"
  repository: "denoland"
  image: "deno"
  tag: "1.45.5"
  pullPolicy: Always
  pullSecrets: "coze-loop-image-secret"

deployment:
  replicaCount: 1
  terminationGracePeriodSeconds: 5

liveness:
  startSeconds: 120
  intervalSeconds: 60
  timeoutSeconds: 20
  shutdownFailureTimes: 20

resources:
  limits:
    memory: "1Gi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

env:
  # Deno 配置
  DENO_DIR: "/tmp/.deno"
  DENO_NO_UPDATE_CHECK: "1"

  # FaaS 基础配置
  FAAS_WORKSPACE: "/tmp/faas-workspace"
  FAAS_PORT: "8000"
  FAAS_TIMEOUT: "30000"
  FAAS_LANGUAGE: "javascript"

# customization
custom:
  image:
    registry:
    pullSecrets:
  resources:
    limits:
      memory:
      cpu:
    requests:
      memory:
      cpu:
