custom:
  image:
    registry: "docker.io"
    pullSecrets: "***"
  faas:
    javascript:
      enabled: true

image:
  repository: denoland/deno
  tag: "1.45.5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

externalService:
  enabled: true
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30891

resources:
  limits:
    memory: "1Gi"
    cpu: "0.5"
  requests:
    memory: "256Mi"
    cpu: "0.25"

env:
  DENO_DIR: "/tmp/.deno"
  DENO_NO_UPDATE_CHECK: "1"
  FAAS_WORKSPACE: "/tmp/faas-workspace"
  FAAS_PORT: "8000"
  FAAS_TIMEOUT: "30000"
  FAAS_LANGUAGE: "javascript"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
    - ALL

probes:
  liveness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

volumes:
  tmp:
    enabled: true
    sizeLimit: "512Mi"

nodeSelector: {}
tolerations: []
affinity: {}