service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

image:
  registry: "denoland"
  repository: "deno"
  image: "deno"
  tag: "1.45.5"
  pullPolicy: IfNotPresent
  pullSecrets: "coze-loop-image-secret"

deployment:
  replicaCount: 1
  terminationGracePeriodSeconds: 5
  resources:
    limits:
      cpu: "0.5"
      memory: "1Gi"
    requests:
      cpu: "0.25"
      memory: "256Mi"

env:
  deno:
    dir: "/tmp/.deno"
    noUpdateCheck: "1"
  faas:
    workspace: "/tmp/faas-workspace"
    port: "8000"
    timeout: "30000"
    language: "javascript"

custom:
  image:
    registry:
    pullSecrets:

