// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/metric/repo (interfaces: IAnnotationMetricRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repo "github.com/coze-dev/coze-loop/backend/modules/observability/domain/metric/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockIAnnotationMetricRepo is a mock of IAnnotationMetricRepo interface.
type MockIAnnotationMetricRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIAnnotationMetricRepoMockRecorder
	isgomock struct{}
}

// MockIAnnotationMetricRepoMockRecorder is the mock recorder for MockIAnnotationMetricRepo.
type MockIAnnotationMetricRepoMockRecorder struct {
	mock *MockIAnnotationMetricRepo
}

// NewMockIAnnotationMetricRepo creates a new mock instance.
func NewMockIAnnotationMetricRepo(ctrl *gomock.Controller) *MockIAnnotationMetricRepo {
	mock := &MockIAnnotationMetricRepo{ctrl: ctrl}
	mock.recorder = &MockIAnnotationMetricRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnnotationMetricRepo) EXPECT() *MockIAnnotationMetricRepoMockRecorder {
	return m.recorder
}

// QueryFeedbackOnlineMetrics mocks base method.
func (m *MockIAnnotationMetricRepo) QueryFeedbackOnlineMetrics(ctx context.Context, param *repo.QueryFeedbackOnlineParam) (*repo.GetMetricsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryFeedbackOnlineMetrics", ctx, param)
	ret0, _ := ret[0].(*repo.GetMetricsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryFeedbackOnlineMetrics indicates an expected call of QueryFeedbackOnlineMetrics.
func (mr *MockIAnnotationMetricRepoMockRecorder) QueryFeedbackOnlineMetrics(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryFeedbackOnlineMetrics", reflect.TypeOf((*MockIAnnotationMetricRepo)(nil).QueryFeedbackOnlineMetrics), ctx, param)
}
