// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql (interfaces: ILabelDAO)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/coze-dev/coze-loop/backend/infra/db"
	mysql "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockILabelDAO is a mock of ILabelDAO interface.
type MockILabelDAO struct {
	ctrl     *gomock.Controller
	recorder *MockILabelDAOMockRecorder
}

// MockILabelDAOMockRecorder is the mock recorder for MockILabelDAO.
type MockILabelDAOMockRecorder struct {
	mock *MockILabelDAO
}

// NewMockILabelDAO creates a new mock instance.
func NewMockILabelDAO(ctrl *gomock.Controller) *MockILabelDAO {
	mock := &MockILabelDAO{ctrl: ctrl}
	mock.recorder = &MockILabelDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILabelDAO) EXPECT() *MockILabelDAOMockRecorder {
	return m.recorder
}

// BatchGet mocks base method.
func (m *MockILabelDAO) BatchGet(arg0 context.Context, arg1 int64, arg2 []string, arg3 ...db.Option) ([]*model.PromptLabel, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchGet", varargs...)
	ret0, _ := ret[0].([]*model.PromptLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGet indicates an expected call of BatchGet.
func (mr *MockILabelDAOMockRecorder) BatchGet(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGet", reflect.TypeOf((*MockILabelDAO)(nil).BatchGet), varargs...)
}

// Create mocks base method.
func (m *MockILabelDAO) Create(arg0 context.Context, arg1 *model.PromptLabel, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockILabelDAOMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockILabelDAO)(nil).Create), varargs...)
}

// List mocks base method.
func (m *MockILabelDAO) List(arg0 context.Context, arg1 mysql.ListLabelDAOParam, arg2 ...db.Option) ([]*model.PromptLabel, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*model.PromptLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockILabelDAOMockRecorder) List(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockILabelDAO)(nil).List), varargs...)
}
