// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql (interfaces: IPromptCommitDAO)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/coze-dev/coze-loop/backend/infra/db"
	mysql "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIPromptCommitDAO is a mock of IPromptCommitDAO interface.
type MockIPromptCommitDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIPromptCommitDAOMockRecorder
}

// MockIPromptCommitDAOMockRecorder is the mock recorder for MockIPromptCommitDAO.
type MockIPromptCommitDAOMockRecorder struct {
	mock *MockIPromptCommitDAO
}

// NewMockIPromptCommitDAO creates a new mock instance.
func NewMockIPromptCommitDAO(ctrl *gomock.Controller) *MockIPromptCommitDAO {
	mock := &MockIPromptCommitDAO{ctrl: ctrl}
	mock.recorder = &MockIPromptCommitDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPromptCommitDAO) EXPECT() *MockIPromptCommitDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPromptCommitDAO) Create(arg0 context.Context, arg1 *model.PromptCommit, arg2 time.Time, arg3 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPromptCommitDAOMockRecorder) Create(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPromptCommitDAO)(nil).Create), varargs...)
}

// Get mocks base method.
func (m *MockIPromptCommitDAO) Get(arg0 context.Context, arg1 int64, arg2 string, arg3 ...db.Option) (*model.PromptCommit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*model.PromptCommit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIPromptCommitDAOMockRecorder) Get(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIPromptCommitDAO)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockIPromptCommitDAO) List(arg0 context.Context, arg1 mysql.ListCommitParam, arg2 ...db.Option) ([]*model.PromptCommit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*model.PromptCommit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIPromptCommitDAOMockRecorder) List(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIPromptCommitDAO)(nil).List), varargs...)
}

// MGet mocks base method.
func (m *MockIPromptCommitDAO) MGet(arg0 context.Context, arg1 []mysql.PromptIDCommitVersionPair, arg2 ...db.Option) (map[mysql.PromptIDCommitVersionPair]*model.PromptCommit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGet", varargs...)
	ret0, _ := ret[0].(map[mysql.PromptIDCommitVersionPair]*model.PromptCommit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGet indicates an expected call of MGet.
func (mr *MockIPromptCommitDAOMockRecorder) MGet(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockIPromptCommitDAO)(nil).MGet), varargs...)
}

// MGetVersionsByPromptID mocks base method.
func (m *MockIPromptCommitDAO) MGetVersionsByPromptID(arg0 context.Context, arg1 int64, arg2 ...db.Option) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGetVersionsByPromptID", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGetVersionsByPromptID indicates an expected call of MGetVersionsByPromptID.
func (mr *MockIPromptCommitDAOMockRecorder) MGetVersionsByPromptID(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGetVersionsByPromptID", reflect.TypeOf((*MockIPromptCommitDAO)(nil).MGetVersionsByPromptID), varargs...)
}
