// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql (interfaces: IPromptBasicDAO)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/coze-dev/coze-loop/backend/infra/db"
	mysql "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIPromptBasicDAO is a mock of IPromptBasicDAO interface.
type MockIPromptBasicDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIPromptBasicDAOMockRecorder
}

// MockIPromptBasicDAOMockRecorder is the mock recorder for MockIPromptBasicDAO.
type MockIPromptBasicDAOMockRecorder struct {
	mock *MockIPromptBasicDAO
}

// NewMockIPromptBasicDAO creates a new mock instance.
func NewMockIPromptBasicDAO(ctrl *gomock.Controller) *MockIPromptBasicDAO {
	mock := &MockIPromptBasicDAO{ctrl: ctrl}
	mock.recorder = &MockIPromptBasicDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPromptBasicDAO) EXPECT() *MockIPromptBasicDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPromptBasicDAO) Create(arg0 context.Context, arg1 *model.PromptBasic, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPromptBasicDAOMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPromptBasicDAO)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockIPromptBasicDAO) Delete(arg0 context.Context, arg1, arg2 int64, arg3 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIPromptBasicDAOMockRecorder) Delete(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIPromptBasicDAO)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockIPromptBasicDAO) Get(arg0 context.Context, arg1 int64, arg2 ...db.Option) (*model.PromptBasic, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*model.PromptBasic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIPromptBasicDAOMockRecorder) Get(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIPromptBasicDAO)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockIPromptBasicDAO) List(arg0 context.Context, arg1 mysql.ListPromptBasicParam, arg2 ...db.Option) ([]*model.PromptBasic, int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*model.PromptBasic)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIPromptBasicDAOMockRecorder) List(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIPromptBasicDAO)(nil).List), varargs...)
}

// MGet mocks base method.
func (m *MockIPromptBasicDAO) MGet(arg0 context.Context, arg1 []int64, arg2 ...db.Option) (map[int64]*model.PromptBasic, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGet", varargs...)
	ret0, _ := ret[0].(map[int64]*model.PromptBasic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGet indicates an expected call of MGet.
func (mr *MockIPromptBasicDAOMockRecorder) MGet(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockIPromptBasicDAO)(nil).MGet), varargs...)
}

// MGetByPromptKey mocks base method.
func (m *MockIPromptBasicDAO) MGetByPromptKey(arg0 context.Context, arg1 int64, arg2 []string, arg3 ...db.Option) ([]*model.PromptBasic, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGetByPromptKey", varargs...)
	ret0, _ := ret[0].([]*model.PromptBasic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGetByPromptKey indicates an expected call of MGetByPromptKey.
func (mr *MockIPromptBasicDAOMockRecorder) MGetByPromptKey(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGetByPromptKey", reflect.TypeOf((*MockIPromptBasicDAO)(nil).MGetByPromptKey), varargs...)
}

// Update mocks base method.
func (m *MockIPromptBasicDAO) Update(arg0 context.Context, arg1 int64, arg2 map[string]interface{}, arg3 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIPromptBasicDAOMockRecorder) Update(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIPromptBasicDAO)(nil).Update), varargs...)
}
