// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql (interfaces: IPromptRelationDAO)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/coze-dev/coze-loop/backend/infra/db"
	mysql "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIPromptRelationDAO is a mock of IPromptRelationDAO interface.
type MockIPromptRelationDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIPromptRelationDAOMockRecorder
}

// MockIPromptRelationDAOMockRecorder is the mock recorder for MockIPromptRelationDAO.
type MockIPromptRelationDAOMockRecorder struct {
	mock *MockIPromptRelationDAO
}

// NewMockIPromptRelationDAO creates a new mock instance.
func NewMockIPromptRelationDAO(ctrl *gomock.Controller) *MockIPromptRelationDAO {
	mock := &MockIPromptRelationDAO{ctrl: ctrl}
	mock.recorder = &MockIPromptRelationDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPromptRelationDAO) EXPECT() *MockIPromptRelationDAOMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockIPromptRelationDAO) BatchCreate(arg0 context.Context, arg1 []*model.PromptRelation, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchCreate", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockIPromptRelationDAOMockRecorder) BatchCreate(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockIPromptRelationDAO)(nil).BatchCreate), varargs...)
}

// BatchDeleteByIDs mocks base method.
func (m *MockIPromptRelationDAO) BatchDeleteByIDs(arg0 context.Context, arg1 []int64, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchDeleteByIDs", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDeleteByIDs indicates an expected call of BatchDeleteByIDs.
func (mr *MockIPromptRelationDAOMockRecorder) BatchDeleteByIDs(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteByIDs", reflect.TypeOf((*MockIPromptRelationDAO)(nil).BatchDeleteByIDs), varargs...)
}

// DeleteByMainPrompt mocks base method.
func (m *MockIPromptRelationDAO) DeleteByMainPrompt(arg0 context.Context, arg1 int64, arg2, arg3 string, arg4 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteByMainPrompt", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMainPrompt indicates an expected call of DeleteByMainPrompt.
func (mr *MockIPromptRelationDAOMockRecorder) DeleteByMainPrompt(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMainPrompt", reflect.TypeOf((*MockIPromptRelationDAO)(nil).DeleteByMainPrompt), varargs...)
}

// List mocks base method.
func (m *MockIPromptRelationDAO) List(arg0 context.Context, arg1 mysql.ListPromptRelationParam, arg2 ...db.Option) ([]*model.PromptRelation, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*model.PromptRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIPromptRelationDAOMockRecorder) List(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIPromptRelationDAO)(nil).List), varargs...)
}
