// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql (interfaces: IPromptUserDraftDAO)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/coze-dev/coze-loop/backend/infra/db"
	mysql "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIPromptUserDraftDAO is a mock of IPromptUserDraftDAO interface.
type MockIPromptUserDraftDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIPromptUserDraftDAOMockRecorder
}

// MockIPromptUserDraftDAOMockRecorder is the mock recorder for MockIPromptUserDraftDAO.
type MockIPromptUserDraftDAOMockRecorder struct {
	mock *MockIPromptUserDraftDAO
}

// NewMockIPromptUserDraftDAO creates a new mock instance.
func NewMockIPromptUserDraftDAO(ctrl *gomock.Controller) *MockIPromptUserDraftDAO {
	mock := &MockIPromptUserDraftDAO{ctrl: ctrl}
	mock.recorder = &MockIPromptUserDraftDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPromptUserDraftDAO) EXPECT() *MockIPromptUserDraftDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPromptUserDraftDAO) Create(arg0 context.Context, arg1 *model.PromptUserDraft, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPromptUserDraftDAOMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPromptUserDraftDAO)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockIPromptUserDraftDAO) Delete(arg0 context.Context, arg1 int64, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIPromptUserDraftDAOMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIPromptUserDraftDAO)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockIPromptUserDraftDAO) Get(arg0 context.Context, arg1 int64, arg2 string, arg3 ...db.Option) (*model.PromptUserDraft, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*model.PromptUserDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIPromptUserDraftDAOMockRecorder) Get(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIPromptUserDraftDAO)(nil).Get), varargs...)
}

// GetByID mocks base method.
func (m *MockIPromptUserDraftDAO) GetByID(arg0 context.Context, arg1 int64, arg2 ...db.Option) (*model.PromptUserDraft, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByID", varargs...)
	ret0, _ := ret[0].(*model.PromptUserDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIPromptUserDraftDAOMockRecorder) GetByID(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIPromptUserDraftDAO)(nil).GetByID), varargs...)
}

// MGet mocks base method.
func (m *MockIPromptUserDraftDAO) MGet(arg0 context.Context, arg1 []mysql.PromptIDUserIDPair, arg2 ...db.Option) (map[mysql.PromptIDUserIDPair]*model.PromptUserDraft, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGet", varargs...)
	ret0, _ := ret[0].(map[mysql.PromptIDUserIDPair]*model.PromptUserDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGet indicates an expected call of MGet.
func (mr *MockIPromptUserDraftDAOMockRecorder) MGet(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockIPromptUserDraftDAO)(nil).MGet), varargs...)
}

// Update mocks base method.
func (m *MockIPromptUserDraftDAO) Update(arg0 context.Context, arg1 *model.PromptUserDraft, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIPromptUserDraftDAOMockRecorder) Update(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIPromptUserDraftDAO)(nil).Update), varargs...)
}
