// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql (interfaces: IToolBasicDAO)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/coze-dev/coze-loop/backend/infra/db"
	mysql "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIToolBasicDAO is a mock of IToolBasicDAO interface.
type MockIToolBasicDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIToolBasicDAOMockRecorder
}

// MockIToolBasicDAOMockRecorder is the mock recorder for MockIToolBasicDAO.
type MockIToolBasicDAOMockRecorder struct {
	mock *MockIToolBasicDAO
}

// NewMockIToolBasicDAO creates a new mock instance.
func NewMockIToolBasicDAO(ctrl *gomock.Controller) *MockIToolBasicDAO {
	mock := &MockIToolBasicDAO{ctrl: ctrl}
	mock.recorder = &MockIToolBasicDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToolBasicDAO) EXPECT() *MockIToolBasicDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIToolBasicDAO) Create(arg0 context.Context, arg1 *model.ToolBasic, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIToolBasicDAOMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIToolBasicDAO)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockIToolBasicDAO) Delete(arg0 context.Context, arg1 int64, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIToolBasicDAOMockRecorder) Delete(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIToolBasicDAO)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockIToolBasicDAO) Get(arg0 context.Context, arg1 int64, arg2 ...db.Option) (*model.ToolBasic, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*model.ToolBasic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIToolBasicDAOMockRecorder) Get(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIToolBasicDAO)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockIToolBasicDAO) List(arg0 context.Context, arg1 mysql.ListToolBasicParam, arg2 ...db.Option) ([]*model.ToolBasic, int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*model.ToolBasic)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIToolBasicDAOMockRecorder) List(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIToolBasicDAO)(nil).List), varargs...)
}

// MGet mocks base method.
func (m *MockIToolBasicDAO) MGet(arg0 context.Context, arg1 []int64, arg2 ...db.Option) (map[int64]*model.ToolBasic, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGet", varargs...)
	ret0, _ := ret[0].(map[int64]*model.ToolBasic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGet indicates an expected call of MGet.
func (mr *MockIToolBasicDAOMockRecorder) MGet(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockIToolBasicDAO)(nil).MGet), varargs...)
}

// Update mocks base method.
func (m *MockIToolBasicDAO) Update(arg0 context.Context, arg1 int64, arg2 map[string]interface{}, arg3 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIToolBasicDAOMockRecorder) Update(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIToolBasicDAO)(nil).Update), varargs...)
}
