// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql (interfaces: IToolCommitDAO)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/coze-dev/coze-loop/backend/infra/db"
	mysql "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/prompt/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIToolCommitDAO is a mock of IToolCommitDAO interface.
type MockIToolCommitDAO struct {
	ctrl     *gomock.Controller
	recorder *MockIToolCommitDAOMockRecorder
}

// MockIToolCommitDAOMockRecorder is the mock recorder for MockIToolCommitDAO.
type MockIToolCommitDAOMockRecorder struct {
	mock *MockIToolCommitDAO
}

// NewMockIToolCommitDAO creates a new mock instance.
func NewMockIToolCommitDAO(ctrl *gomock.Controller) *MockIToolCommitDAO {
	mock := &MockIToolCommitDAO{ctrl: ctrl}
	mock.recorder = &MockIToolCommitDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToolCommitDAO) EXPECT() *MockIToolCommitDAOMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIToolCommitDAO) Create(arg0 context.Context, arg1 *model.ToolCommit, arg2 time.Time, arg3 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIToolCommitDAOMockRecorder) Create(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIToolCommitDAO)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockIToolCommitDAO) Delete(arg0 context.Context, arg1 int64, arg2 string, arg3 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIToolCommitDAOMockRecorder) Delete(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIToolCommitDAO)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockIToolCommitDAO) Get(arg0 context.Context, arg1 int64, arg2 string, arg3 ...db.Option) (*model.ToolCommit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*model.ToolCommit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIToolCommitDAOMockRecorder) Get(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIToolCommitDAO)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockIToolCommitDAO) List(arg0 context.Context, arg1 mysql.ListToolCommitDAOParam, arg2 ...db.Option) ([]*model.ToolCommit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*model.ToolCommit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIToolCommitDAOMockRecorder) List(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIToolCommitDAO)(nil).List), varargs...)
}

// MGet mocks base method.
func (m *MockIToolCommitDAO) MGet(arg0 context.Context, arg1 []mysql.ToolIDVersionPair, arg2 ...db.Option) (map[mysql.ToolIDVersionPair]*model.ToolCommit, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGet", varargs...)
	ret0, _ := ret[0].(map[mysql.ToolIDVersionPair]*model.ToolCommit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGet indicates an expected call of MGet.
func (mr *MockIToolCommitDAOMockRecorder) MGet(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockIToolCommitDAO)(nil).MGet), varargs...)
}

// Upsert mocks base method.
func (m *MockIToolCommitDAO) Upsert(arg0 context.Context, arg1 *model.ToolCommit, arg2 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upsert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockIToolCommitDAOMockRecorder) Upsert(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockIToolCommitDAO)(nil).Upsert), varargs...)
}
