service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

image:
  registry: "docker.io"
  repository: "cozedev"
  image: "coze-loop-python-faas"
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets: "coze-loop-image-secret"

deployment:
  replicaCount: 1
  terminationGracePeriodSeconds: 5

liveness:
  startSeconds: 120
  intervalSeconds: 60
  timeoutSeconds: 20
  shutdownFailureTimes: 20

resources:
  limits:
    memory: "4Gi"
    cpu: "2"
  requests:
    memory: "2Gi"
    cpu: "1"

env:
  # Deno 配置
  DENO_DIR: "/tmp/faas-workspace/.deno"
  DENO_NO_UPDATE_CHECK: "1"
  DENO_V8_FLAGS: "--max-old-space-size=2048"
  PYODIDE_IMPORT_MAP: "/app/vendor/import_map.json"

  # FaaS 基础配置
  FAAS_WORKSPACE: "/tmp/faas-workspace"
  FAAS_PORT: "8000"
  FAAS_TIMEOUT: "30000"
  FAAS_LANGUAGE: "python"

  # 预装Python包版本配置（使用兼容版本）
  NUMPY_VERSION: ">=1.24.0"
  PANDAS_VERSION: ">=1.5.0"
  JSONSCHEMA_VERSION: ">=4.0.0"
  SCIPY_VERSION: ">=1.10.0"
  SKLEARN_VERSION: ">=1.3.0"

# customization
custom:
  image:
    registry:
    pullSecrets:
  resources:
    limits:
      memory:
      cpu:
    requests:
      memory:
      cpu:
