// Code generated by tool. DO NOT EDIT.
// app: cozeloop, biz: llm

package errno

import (
	"github.com/coze-dev/coze-loop/backend/pkg/errorx/code"
)

const (
	CommonNoPermissionCode              = 601500101
	commonNoPermissionMessage           = "no access permission"
	commonNoPermissionNoAffectStability = true

	CommonBadRequestCode              = 601500201
	commonBadRequestMessage           = "bad request"
	commonBadRequestNoAffectStability = true

	CommonInvalidParamCode              = 601500202
	commonInvalidParamMessage           = "invalid param"
	commonInvalidParamNoAffectStability = true

	CommonBizInvalidCode              = 601500203
	commonBizInvalidMessage           = "biz operation is not allowed"
	commonBizInvalidNoAffectStability = true

	CommonResourceDuplicatedCode              = 601500204
	commonResourceDuplicatedMessage           = "resource duplicated"
	commonResourceDuplicatedNoAffectStability = true

	CommonNetworkTimeOutCode              = 601500701
	commonNetworkTimeOutMessage           = "network timeout"
	commonNetworkTimeOutNoAffectStability = false

	CommonInternalErrorCode              = 601500702
	commonInternalErrorMessage           = "internal error"
	commonInternalErrorNoAffectStability = false

	CommonRPCErrorCode              = 601500703
	commonRPCErrorMessage           = "rpc error"
	commonRPCErrorNoAffectStability = false

	CommonMySqlErrorCode              = 601500801
	commonMySqlErrorMessage           = "mysql error"
	commonMySqlErrorNoAffectStability = false

	CommonRedisErrorCode              = 601500803
	commonRedisErrorMessage           = "redis error"
	commonRedisErrorNoAffectStability = false

	UnknownErrCode              = 601505001
	unknownErrMessage           = "unknown err occurred, please oncall"
	unknownErrNoAffectStability = false

	ResourceNotFoundCode              = 601505002
	resourceNotFoundMessage           = "resource not found"
	resourceNotFoundNoAffectStability = true

	ModelQPMLimitCode              = 601505003
	modelQPMLimitMessage           = "request is limited, because qpm of current model reached the upper limit"
	modelQPMLimitNoAffectStability = true

	ModelTPMLimitCode              = 601505004
	modelTPMLimitMessage           = "request is limited, because tpm of current model reached the upper limit"
	modelTPMLimitNoAffectStability = true

	ModelInvalidCode              = 601505005
	modelInvalidMessage           = "model is invalid"
	modelInvalidNoAffectStability = true

	BuildLLMFailedCode              = 601505006
	buildLLMFailedMessage           = "build llm failed"
	buildLLMFailedNoAffectStability = false

	RequestNotValidCode              = 601505007
	requestNotValidMessage           = "request not valid"
	requestNotValidNoAffectStability = true

	RequestNotCompatibleWithModelAbilityCode              = 601505008
	requestNotCompatibleWithModelAbilityMessage           = "request is not compatible with model ability"
	requestNotCompatibleWithModelAbilityNoAffectStability = true

	CallModelFailedCode              = 601505009
	callModelFailedMessage           = "call model failed"
	callModelFailedNoAffectStability = false

	ParseModelRespFailedCode              = 601505010
	parseModelRespFailedMessage           = "parse model response failed"
	parseModelRespFailedNoAffectStability = false

	RiskContentDetectedCode              = 601505011
	riskContentDetectedMessage           = "risk content is detected"
	riskContentDetectedNoAffectStability = true

	CallModelTimeoutCode              = 601505012
	callModelTimeoutMessage           = "call model timeout"
	callModelTimeoutNoAffectStability = true

	CozeModelNotExistCode              = 601505101 // Coze模型不存在
	cozeModelNotExistMessage           = "coze model not exist"
	cozeModelNotExistNoAffectStability = true

	InterfaceNotAvailableInHouseCode              = 601505102 // 当前接口不支持Coze罗盘内场
	interfaceNotAvailableInHouseMessage           = "the interface is not available in house"
	interfaceNotAvailableInHouseNoAffectStability = true

	GetCozeModelListFailedCode              = 601505103 // 请求Coze模型列表接口失败
	getCozeModelListFailedMessage           = "get coze model list failed"
	getCozeModelListFailedNoAffectStability = true

	GetCozeModelFailedCode              = 601505104 // 请求Coze模型详情接口失败
	getCozeModelFailedMessage           = "get coze model failed"
	getCozeModelFailedNoAffectStability = true

	GetCozeModelListParamFailedCode              = 601505105 // 请求Coze模型列表参数接口失败
	getCozeModelListParamFailedMessage           = "get coze model list param failed"
	getCozeModelListParamFailedNoAffectStability = true

	GetCozeModelUsageFailedCode              = 601505106 // 请求Coze模型用量接口失败
	getCozeModelUsageFailedMessage           = "get coze model usage failed"
	getCozeModelUsageFailedNoAffectStability = true

	GetLLMGatewayModelConfigFailedCode              = 601505107 // 获取LLM Gateway模型配置失败
	getLLMGatewayModelConfigFailedMessage           = "get llm gateway model config failed"
	getLLMGatewayModelConfigFailedNoAffectStability = true
)

func init() {

	code.Register(
		CommonNoPermissionCode,
		commonNoPermissionMessage,
		code.WithAffectStability(!commonNoPermissionNoAffectStability),
	)

	code.Register(
		CommonBadRequestCode,
		commonBadRequestMessage,
		code.WithAffectStability(!commonBadRequestNoAffectStability),
	)

	code.Register(
		CommonInvalidParamCode,
		commonInvalidParamMessage,
		code.WithAffectStability(!commonInvalidParamNoAffectStability),
	)

	code.Register(
		CommonBizInvalidCode,
		commonBizInvalidMessage,
		code.WithAffectStability(!commonBizInvalidNoAffectStability),
	)

	code.Register(
		CommonResourceDuplicatedCode,
		commonResourceDuplicatedMessage,
		code.WithAffectStability(!commonResourceDuplicatedNoAffectStability),
	)

	code.Register(
		CommonNetworkTimeOutCode,
		commonNetworkTimeOutMessage,
		code.WithAffectStability(!commonNetworkTimeOutNoAffectStability),
	)

	code.Register(
		CommonInternalErrorCode,
		commonInternalErrorMessage,
		code.WithAffectStability(!commonInternalErrorNoAffectStability),
	)

	code.Register(
		CommonRPCErrorCode,
		commonRPCErrorMessage,
		code.WithAffectStability(!commonRPCErrorNoAffectStability),
	)

	code.Register(
		CommonMySqlErrorCode,
		commonMySqlErrorMessage,
		code.WithAffectStability(!commonMySqlErrorNoAffectStability),
	)

	code.Register(
		CommonRedisErrorCode,
		commonRedisErrorMessage,
		code.WithAffectStability(!commonRedisErrorNoAffectStability),
	)

	code.Register(
		UnknownErrCode,
		unknownErrMessage,
		code.WithAffectStability(!unknownErrNoAffectStability),
	)

	code.Register(
		ResourceNotFoundCode,
		resourceNotFoundMessage,
		code.WithAffectStability(!resourceNotFoundNoAffectStability),
	)

	code.Register(
		ModelQPMLimitCode,
		modelQPMLimitMessage,
		code.WithAffectStability(!modelQPMLimitNoAffectStability),
	)

	code.Register(
		ModelTPMLimitCode,
		modelTPMLimitMessage,
		code.WithAffectStability(!modelTPMLimitNoAffectStability),
	)

	code.Register(
		ModelInvalidCode,
		modelInvalidMessage,
		code.WithAffectStability(!modelInvalidNoAffectStability),
	)

	code.Register(
		BuildLLMFailedCode,
		buildLLMFailedMessage,
		code.WithAffectStability(!buildLLMFailedNoAffectStability),
	)

	code.Register(
		RequestNotValidCode,
		requestNotValidMessage,
		code.WithAffectStability(!requestNotValidNoAffectStability),
	)

	code.Register(
		RequestNotCompatibleWithModelAbilityCode,
		requestNotCompatibleWithModelAbilityMessage,
		code.WithAffectStability(!requestNotCompatibleWithModelAbilityNoAffectStability),
	)

	code.Register(
		CallModelFailedCode,
		callModelFailedMessage,
		code.WithAffectStability(!callModelFailedNoAffectStability),
	)

	code.Register(
		ParseModelRespFailedCode,
		parseModelRespFailedMessage,
		code.WithAffectStability(!parseModelRespFailedNoAffectStability),
	)

	code.Register(
		RiskContentDetectedCode,
		riskContentDetectedMessage,
		code.WithAffectStability(!riskContentDetectedNoAffectStability),
	)

	code.Register(
		CallModelTimeoutCode,
		callModelTimeoutMessage,
		code.WithAffectStability(!callModelTimeoutNoAffectStability),
	)

	code.Register(
		CozeModelNotExistCode,
		cozeModelNotExistMessage,
		code.WithAffectStability(!cozeModelNotExistNoAffectStability),
	)

	code.Register(
		InterfaceNotAvailableInHouseCode,
		interfaceNotAvailableInHouseMessage,
		code.WithAffectStability(!interfaceNotAvailableInHouseNoAffectStability),
	)

	code.Register(
		GetCozeModelListFailedCode,
		getCozeModelListFailedMessage,
		code.WithAffectStability(!getCozeModelListFailedNoAffectStability),
	)

	code.Register(
		GetCozeModelFailedCode,
		getCozeModelFailedMessage,
		code.WithAffectStability(!getCozeModelFailedNoAffectStability),
	)

	code.Register(
		GetCozeModelListParamFailedCode,
		getCozeModelListParamFailedMessage,
		code.WithAffectStability(!getCozeModelListParamFailedNoAffectStability),
	)

	code.Register(
		GetCozeModelUsageFailedCode,
		getCozeModelUsageFailedMessage,
		code.WithAffectStability(!getCozeModelUsageFailedNoAffectStability),
	)

	code.Register(
		GetLLMGatewayModelConfigFailedCode,
		getLLMGatewayModelConfigFailedMessage,
		code.WithAffectStability(!getLLMGatewayModelConfigFailedNoAffectStability),
	)

}
