// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/domain/service (interfaces: IPromptService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/entity"
	service "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockIPromptService is a mock of IPromptService interface.
type MockIPromptService struct {
	ctrl     *gomock.Controller
	recorder *MockIPromptServiceMockRecorder
}

// MockIPromptServiceMockRecorder is the mock recorder for MockIPromptService.
type MockIPromptServiceMockRecorder struct {
	mock *MockIPromptService
}

// NewMockIPromptService creates a new mock instance.
func NewMockIPromptService(ctrl *gomock.Controller) *MockIPromptService {
	mock := &MockIPromptService{ctrl: ctrl}
	mock.recorder = &MockIPromptServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPromptService) EXPECT() *MockIPromptServiceMockRecorder {
	return m.recorder
}

// BatchGetCommitLabels mocks base method.
func (m *MockIPromptService) BatchGetCommitLabels(arg0 context.Context, arg1 int64, arg2 []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetCommitLabels", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetCommitLabels indicates an expected call of BatchGetCommitLabels.
func (mr *MockIPromptServiceMockRecorder) BatchGetCommitLabels(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetCommitLabels", reflect.TypeOf((*MockIPromptService)(nil).BatchGetCommitLabels), arg0, arg1, arg2)
}

// BatchGetLabelMappingPromptVersion mocks base method.
func (m *MockIPromptService) BatchGetLabelMappingPromptVersion(arg0 context.Context, arg1 []service.PromptLabelQuery) (map[service.PromptLabelQuery]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetLabelMappingPromptVersion", arg0, arg1)
	ret0, _ := ret[0].(map[service.PromptLabelQuery]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetLabelMappingPromptVersion indicates an expected call of BatchGetLabelMappingPromptVersion.
func (mr *MockIPromptServiceMockRecorder) BatchGetLabelMappingPromptVersion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetLabelMappingPromptVersion", reflect.TypeOf((*MockIPromptService)(nil).BatchGetLabelMappingPromptVersion), arg0, arg1)
}

// CreateLabel mocks base method.
func (m *MockIPromptService) CreateLabel(arg0 context.Context, arg1 *entity.PromptLabel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockIPromptServiceMockRecorder) CreateLabel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockIPromptService)(nil).CreateLabel), arg0, arg1)
}

// CreatePrompt mocks base method.
func (m *MockIPromptService) CreatePrompt(arg0 context.Context, arg1 *entity.Prompt) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrompt", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrompt indicates an expected call of CreatePrompt.
func (mr *MockIPromptServiceMockRecorder) CreatePrompt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrompt", reflect.TypeOf((*MockIPromptService)(nil).CreatePrompt), arg0, arg1)
}

// Execute mocks base method.
func (m *MockIPromptService) Execute(arg0 context.Context, arg1 service.ExecuteParam) (*entity.Reply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*entity.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIPromptServiceMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIPromptService)(nil).Execute), arg0, arg1)
}

// ExecuteStreaming mocks base method.
func (m *MockIPromptService) ExecuteStreaming(arg0 context.Context, arg1 service.ExecuteStreamingParam) (*entity.Reply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStreaming", arg0, arg1)
	ret0, _ := ret[0].(*entity.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteStreaming indicates an expected call of ExecuteStreaming.
func (mr *MockIPromptServiceMockRecorder) ExecuteStreaming(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStreaming", reflect.TypeOf((*MockIPromptService)(nil).ExecuteStreaming), arg0, arg1)
}

// ExpandSnippets mocks base method.
func (m *MockIPromptService) ExpandSnippets(arg0 context.Context, arg1 *entity.Prompt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandSnippets", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpandSnippets indicates an expected call of ExpandSnippets.
func (mr *MockIPromptServiceMockRecorder) ExpandSnippets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandSnippets", reflect.TypeOf((*MockIPromptService)(nil).ExpandSnippets), arg0, arg1)
}

// FormatPrompt mocks base method.
func (m *MockIPromptService) FormatPrompt(arg0 context.Context, arg1 *entity.Prompt, arg2 []*entity.Message, arg3 []*entity.VariableVal) ([]*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatPrompt", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FormatPrompt indicates an expected call of FormatPrompt.
func (mr *MockIPromptServiceMockRecorder) FormatPrompt(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatPrompt", reflect.TypeOf((*MockIPromptService)(nil).FormatPrompt), arg0, arg1, arg2, arg3)
}

// GetPrompt mocks base method.
func (m *MockIPromptService) GetPrompt(arg0 context.Context, arg1 service.GetPromptParam) (*entity.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrompt", arg0, arg1)
	ret0, _ := ret[0].(*entity.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrompt indicates an expected call of GetPrompt.
func (mr *MockIPromptServiceMockRecorder) GetPrompt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrompt", reflect.TypeOf((*MockIPromptService)(nil).GetPrompt), arg0, arg1)
}

// ListLabel mocks base method.
func (m *MockIPromptService) ListLabel(arg0 context.Context, arg1 service.ListLabelParam) ([]*entity.PromptLabel, *int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabel", arg0, arg1)
	ret0, _ := ret[0].([]*entity.PromptLabel)
	ret1, _ := ret[1].(*int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLabel indicates an expected call of ListLabel.
func (mr *MockIPromptServiceMockRecorder) ListLabel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabel", reflect.TypeOf((*MockIPromptService)(nil).ListLabel), arg0, arg1)
}

// MCompleteMultiModalFileURL mocks base method.
func (m *MockIPromptService) MCompleteMultiModalFileURL(arg0 context.Context, arg1 []*entity.Message, arg2 []*entity.VariableVal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MCompleteMultiModalFileURL", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MCompleteMultiModalFileURL indicates an expected call of MCompleteMultiModalFileURL.
func (mr *MockIPromptServiceMockRecorder) MCompleteMultiModalFileURL(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MCompleteMultiModalFileURL", reflect.TypeOf((*MockIPromptService)(nil).MCompleteMultiModalFileURL), arg0, arg1, arg2)
}

// MConvertBase64DataURLToFileURI mocks base method.
func (m *MockIPromptService) MConvertBase64DataURLToFileURI(arg0 context.Context, arg1 []*entity.Message, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MConvertBase64DataURLToFileURI", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MConvertBase64DataURLToFileURI indicates an expected call of MConvertBase64DataURLToFileURI.
func (mr *MockIPromptServiceMockRecorder) MConvertBase64DataURLToFileURI(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MConvertBase64DataURLToFileURI", reflect.TypeOf((*MockIPromptService)(nil).MConvertBase64DataURLToFileURI), arg0, arg1, arg2)
}

// MConvertBase64DataURLToFileURL mocks base method.
func (m *MockIPromptService) MConvertBase64DataURLToFileURL(arg0 context.Context, arg1 []*entity.Message, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MConvertBase64DataURLToFileURL", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MConvertBase64DataURLToFileURL indicates an expected call of MConvertBase64DataURLToFileURL.
func (mr *MockIPromptServiceMockRecorder) MConvertBase64DataURLToFileURL(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MConvertBase64DataURLToFileURL", reflect.TypeOf((*MockIPromptService)(nil).MConvertBase64DataURLToFileURL), arg0, arg1, arg2)
}

// MGetPromptIDs mocks base method.
func (m *MockIPromptService) MGetPromptIDs(arg0 context.Context, arg1 int64, arg2 []string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MGetPromptIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGetPromptIDs indicates an expected call of MGetPromptIDs.
func (mr *MockIPromptServiceMockRecorder) MGetPromptIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGetPromptIDs", reflect.TypeOf((*MockIPromptService)(nil).MGetPromptIDs), arg0, arg1, arg2)
}

// MParseCommitVersion mocks base method.
func (m *MockIPromptService) MParseCommitVersion(arg0 context.Context, arg1 int64, arg2 []service.PromptQueryParam) (map[service.PromptQueryParam]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MParseCommitVersion", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[service.PromptQueryParam]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MParseCommitVersion indicates an expected call of MParseCommitVersion.
func (mr *MockIPromptServiceMockRecorder) MParseCommitVersion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MParseCommitVersion", reflect.TypeOf((*MockIPromptService)(nil).MParseCommitVersion), arg0, arg1, arg2)
}

// SaveDraft mocks base method.
func (m *MockIPromptService) SaveDraft(arg0 context.Context, arg1 *entity.Prompt) (*entity.DraftInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDraft", arg0, arg1)
	ret0, _ := ret[0].(*entity.DraftInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveDraft indicates an expected call of SaveDraft.
func (mr *MockIPromptServiceMockRecorder) SaveDraft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDraft", reflect.TypeOf((*MockIPromptService)(nil).SaveDraft), arg0, arg1)
}

// UpdateCommitLabels mocks base method.
func (m *MockIPromptService) UpdateCommitLabels(arg0 context.Context, arg1 service.UpdateCommitLabelsParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommitLabels", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommitLabels indicates an expected call of UpdateCommitLabels.
func (mr *MockIPromptServiceMockRecorder) UpdateCommitLabels(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommitLabels", reflect.TypeOf((*MockIPromptService)(nil).UpdateCommitLabels), arg0, arg1)
}

// ValidateLabelsExist mocks base method.
func (m *MockIPromptService) ValidateLabelsExist(arg0 context.Context, arg1 int64, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLabelsExist", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateLabelsExist indicates an expected call of ValidateLabelsExist.
func (mr *MockIPromptServiceMockRecorder) ValidateLabelsExist(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLabelsExist", reflect.TypeOf((*MockIPromptService)(nil).ValidateLabelsExist), arg0, arg1, arg2)
}
