// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/domain/service (interfaces: IToolService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockIToolService is a mock of IToolService interface.
type MockIToolService struct {
	ctrl     *gomock.Controller
	recorder *MockIToolServiceMockRecorder
}

// MockIToolServiceMockRecorder is the mock recorder for MockIToolService.
type MockIToolServiceMockRecorder struct {
	mock *MockIToolService
}

// NewMockIToolService creates a new mock instance.
func NewMockIToolService(ctrl *gomock.Controller) *MockIToolService {
	mock := &MockIToolService{ctrl: ctrl}
	mock.recorder = &MockIToolServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToolService) EXPECT() *MockIToolServiceMockRecorder {
	return m.recorder
}

// CreateTool mocks base method.
func (m *MockIToolService) CreateTool(arg0 context.Context, arg1 *entity.CommonTool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTool", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTool indicates an expected call of CreateTool.
func (mr *MockIToolServiceMockRecorder) CreateTool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTool", reflect.TypeOf((*MockIToolService)(nil).CreateTool), arg0, arg1)
}
