// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql/gorm_gen/model"
)

func newObservabilityTask(db *gorm.DB, opts ...gen.DOOption) observabilityTask {
	_observabilityTask := observabilityTask{}

	_observabilityTask.observabilityTaskDo.UseDB(db, opts...)
	_observabilityTask.observabilityTaskDo.UseModel(&model.ObservabilityTask{})

	tableName := _observabilityTask.observabilityTaskDo.TableName()
	_observabilityTask.ALL = field.NewAsterisk(tableName)

	_observabilityTask.fillFieldMap()

	return _observabilityTask
}

type observabilityTask struct {
	observabilityTaskDo observabilityTaskDo

	ALL field.Asterisk

	fieldMap map[string]field.Expr
}

func (o observabilityTask) Table(newTableName string) *observabilityTask {
	o.observabilityTaskDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o observabilityTask) As(alias string) *observabilityTask {
	o.observabilityTaskDo.DO = *(o.observabilityTaskDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *observabilityTask) updateTableName(table string) *observabilityTask {
	o.ALL = field.NewAsterisk(table)

	o.fillFieldMap()

	return o
}

func (o *observabilityTask) WithContext(ctx context.Context) *observabilityTaskDo {
	return o.observabilityTaskDo.WithContext(ctx)
}

func (o observabilityTask) TableName() string { return o.observabilityTaskDo.TableName() }

func (o observabilityTask) Alias() string { return o.observabilityTaskDo.Alias() }

func (o observabilityTask) Columns(cols ...field.Expr) gen.Columns {
	return o.observabilityTaskDo.Columns(cols...)
}

func (o *observabilityTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *observabilityTask) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 0)
}

func (o observabilityTask) clone(db *gorm.DB) observabilityTask {
	o.observabilityTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o observabilityTask) replaceDB(db *gorm.DB) observabilityTask {
	o.observabilityTaskDo.ReplaceDB(db)
	return o
}

type observabilityTaskDo struct{ gen.DO }

func (o observabilityTaskDo) Debug() *observabilityTaskDo {
	return o.withDO(o.DO.Debug())
}

func (o observabilityTaskDo) WithContext(ctx context.Context) *observabilityTaskDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o observabilityTaskDo) ReadDB() *observabilityTaskDo {
	return o.Clauses(dbresolver.Read)
}

func (o observabilityTaskDo) WriteDB() *observabilityTaskDo {
	return o.Clauses(dbresolver.Write)
}

func (o observabilityTaskDo) Session(config *gorm.Session) *observabilityTaskDo {
	return o.withDO(o.DO.Session(config))
}

func (o observabilityTaskDo) Clauses(conds ...clause.Expression) *observabilityTaskDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o observabilityTaskDo) Returning(value interface{}, columns ...string) *observabilityTaskDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o observabilityTaskDo) Not(conds ...gen.Condition) *observabilityTaskDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o observabilityTaskDo) Or(conds ...gen.Condition) *observabilityTaskDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o observabilityTaskDo) Select(conds ...field.Expr) *observabilityTaskDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o observabilityTaskDo) Where(conds ...gen.Condition) *observabilityTaskDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o observabilityTaskDo) Order(conds ...field.Expr) *observabilityTaskDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o observabilityTaskDo) Distinct(cols ...field.Expr) *observabilityTaskDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o observabilityTaskDo) Omit(cols ...field.Expr) *observabilityTaskDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o observabilityTaskDo) Join(table schema.Tabler, on ...field.Expr) *observabilityTaskDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o observabilityTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *observabilityTaskDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o observabilityTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *observabilityTaskDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o observabilityTaskDo) Group(cols ...field.Expr) *observabilityTaskDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o observabilityTaskDo) Having(conds ...gen.Condition) *observabilityTaskDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o observabilityTaskDo) Limit(limit int) *observabilityTaskDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o observabilityTaskDo) Offset(offset int) *observabilityTaskDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o observabilityTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *observabilityTaskDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o observabilityTaskDo) Unscoped() *observabilityTaskDo {
	return o.withDO(o.DO.Unscoped())
}

func (o observabilityTaskDo) Create(values ...*model.ObservabilityTask) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o observabilityTaskDo) CreateInBatches(values []*model.ObservabilityTask, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o observabilityTaskDo) Save(values ...*model.ObservabilityTask) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o observabilityTaskDo) First() (*model.ObservabilityTask, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityTask), nil
	}
}

func (o observabilityTaskDo) Take() (*model.ObservabilityTask, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityTask), nil
	}
}

func (o observabilityTaskDo) Last() (*model.ObservabilityTask, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityTask), nil
	}
}

func (o observabilityTaskDo) Find() ([]*model.ObservabilityTask, error) {
	result, err := o.DO.Find()
	return result.([]*model.ObservabilityTask), err
}

func (o observabilityTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ObservabilityTask, err error) {
	buf := make([]*model.ObservabilityTask, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o observabilityTaskDo) FindInBatches(result *[]*model.ObservabilityTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o observabilityTaskDo) Attrs(attrs ...field.AssignExpr) *observabilityTaskDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o observabilityTaskDo) Assign(attrs ...field.AssignExpr) *observabilityTaskDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o observabilityTaskDo) Joins(fields ...field.RelationField) *observabilityTaskDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o observabilityTaskDo) Preload(fields ...field.RelationField) *observabilityTaskDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o observabilityTaskDo) FirstOrInit() (*model.ObservabilityTask, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityTask), nil
	}
}

func (o observabilityTaskDo) FirstOrCreate() (*model.ObservabilityTask, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityTask), nil
	}
}

func (o observabilityTaskDo) FindByPage(offset int, limit int) (result []*model.ObservabilityTask, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o observabilityTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o observabilityTaskDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o observabilityTaskDo) Delete(models ...*model.ObservabilityTask) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *observabilityTaskDo) withDO(do gen.Dao) *observabilityTaskDo {
	o.DO = *do.(*gen.DO)
	return o
}
