// Code generated by Kitex v0.13.1. DO NOT EDIT.

package toolmanageservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	manage "github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/prompt/tool/manage"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateTool": kitex.NewMethodInfo(
		createToolHandler,
		newToolManageServiceCreateToolArgs,
		newToolManageServiceCreateToolResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetToolDetail": kitex.NewMethodInfo(
		getToolDetailHandler,
		newToolManageServiceGetToolDetailArgs,
		newToolManageServiceGetToolDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListTool": kitex.NewMethodInfo(
		listToolHandler,
		newToolManageServiceListToolArgs,
		newToolManageServiceListToolResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SaveToolDetail": kitex.NewMethodInfo(
		saveToolDetailHandler,
		newToolManageServiceSaveToolDetailArgs,
		newToolManageServiceSaveToolDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommitToolDraft": kitex.NewMethodInfo(
		commitToolDraftHandler,
		newToolManageServiceCommitToolDraftArgs,
		newToolManageServiceCommitToolDraftResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListToolCommit": kitex.NewMethodInfo(
		listToolCommitHandler,
		newToolManageServiceListToolCommitArgs,
		newToolManageServiceListToolCommitResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	toolManageServiceServiceInfo = NewServiceInfo()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return toolManageServiceServiceInfo
}

// NewServiceInfo creates a new ServiceInfo
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo()
}

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "ToolManageService"
	handlerType := (*manage.ToolManageService)(nil)
	extra := map[string]interface{}{
		"PackageName": "manage",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         serviceMethods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func createToolHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*manage.ToolManageServiceCreateToolArgs)
	realResult := result.(*manage.ToolManageServiceCreateToolResult)
	success, err := handler.(manage.ToolManageService).CreateTool(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newToolManageServiceCreateToolArgs() interface{} {
	return manage.NewToolManageServiceCreateToolArgs()
}

func newToolManageServiceCreateToolResult() interface{} {
	return manage.NewToolManageServiceCreateToolResult()
}

func getToolDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*manage.ToolManageServiceGetToolDetailArgs)
	realResult := result.(*manage.ToolManageServiceGetToolDetailResult)
	success, err := handler.(manage.ToolManageService).GetToolDetail(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newToolManageServiceGetToolDetailArgs() interface{} {
	return manage.NewToolManageServiceGetToolDetailArgs()
}

func newToolManageServiceGetToolDetailResult() interface{} {
	return manage.NewToolManageServiceGetToolDetailResult()
}

func listToolHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*manage.ToolManageServiceListToolArgs)
	realResult := result.(*manage.ToolManageServiceListToolResult)
	success, err := handler.(manage.ToolManageService).ListTool(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newToolManageServiceListToolArgs() interface{} {
	return manage.NewToolManageServiceListToolArgs()
}

func newToolManageServiceListToolResult() interface{} {
	return manage.NewToolManageServiceListToolResult()
}

func saveToolDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*manage.ToolManageServiceSaveToolDetailArgs)
	realResult := result.(*manage.ToolManageServiceSaveToolDetailResult)
	success, err := handler.(manage.ToolManageService).SaveToolDetail(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newToolManageServiceSaveToolDetailArgs() interface{} {
	return manage.NewToolManageServiceSaveToolDetailArgs()
}

func newToolManageServiceSaveToolDetailResult() interface{} {
	return manage.NewToolManageServiceSaveToolDetailResult()
}

func commitToolDraftHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*manage.ToolManageServiceCommitToolDraftArgs)
	realResult := result.(*manage.ToolManageServiceCommitToolDraftResult)
	success, err := handler.(manage.ToolManageService).CommitToolDraft(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newToolManageServiceCommitToolDraftArgs() interface{} {
	return manage.NewToolManageServiceCommitToolDraftArgs()
}

func newToolManageServiceCommitToolDraftResult() interface{} {
	return manage.NewToolManageServiceCommitToolDraftResult()
}

func listToolCommitHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*manage.ToolManageServiceListToolCommitArgs)
	realResult := result.(*manage.ToolManageServiceListToolCommitResult)
	success, err := handler.(manage.ToolManageService).ListToolCommit(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newToolManageServiceListToolCommitArgs() interface{} {
	return manage.NewToolManageServiceListToolCommitArgs()
}

func newToolManageServiceListToolCommitResult() interface{} {
	return manage.NewToolManageServiceListToolCommitResult()
}

type kClient struct {
	c  client.Client
	sc client.Streaming
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c:  c,
		sc: c.(client.Streaming),
	}
}

func (p *kClient) CreateTool(ctx context.Context, request *manage.CreateToolRequest) (r *manage.CreateToolResponse, err error) {
	var _args manage.ToolManageServiceCreateToolArgs
	_args.Request = request
	var _result manage.ToolManageServiceCreateToolResult
	if err = p.c.Call(ctx, "CreateTool", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetToolDetail(ctx context.Context, request *manage.GetToolDetailRequest) (r *manage.GetToolDetailResponse, err error) {
	var _args manage.ToolManageServiceGetToolDetailArgs
	_args.Request = request
	var _result manage.ToolManageServiceGetToolDetailResult
	if err = p.c.Call(ctx, "GetToolDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListTool(ctx context.Context, request *manage.ListToolRequest) (r *manage.ListToolResponse, err error) {
	var _args manage.ToolManageServiceListToolArgs
	_args.Request = request
	var _result manage.ToolManageServiceListToolResult
	if err = p.c.Call(ctx, "ListTool", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SaveToolDetail(ctx context.Context, request *manage.SaveToolDetailRequest) (r *manage.SaveToolDetailResponse, err error) {
	var _args manage.ToolManageServiceSaveToolDetailArgs
	_args.Request = request
	var _result manage.ToolManageServiceSaveToolDetailResult
	if err = p.c.Call(ctx, "SaveToolDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommitToolDraft(ctx context.Context, request *manage.CommitToolDraftRequest) (r *manage.CommitToolDraftResponse, err error) {
	var _args manage.ToolManageServiceCommitToolDraftArgs
	_args.Request = request
	var _result manage.ToolManageServiceCommitToolDraftResult
	if err = p.c.Call(ctx, "CommitToolDraft", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListToolCommit(ctx context.Context, request *manage.ListToolCommitRequest) (r *manage.ListToolCommitResponse, err error) {
	var _args manage.ToolManageServiceListToolCommitArgs
	_args.Request = request
	var _result manage.ToolManageServiceListToolCommitResult
	if err = p.c.Call(ctx, "ListToolCommit", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
