// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/component/task (interfaces: ITaskHookProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/task_hook.go -package=mocks . ITaskHookProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	task "github.com/coze-dev/coze-loop/backend/modules/observability/domain/component/task"
	gomock "go.uber.org/mock/gomock"
)

// MockITaskHookProvider is a mock of ITaskHookProvider interface.
type MockITaskHookProvider struct {
	ctrl     *gomock.Controller
	recorder *MockITaskHookProviderMockRecorder
	isgomock struct{}
}

// MockITaskHookProviderMockRecorder is the mock recorder for MockITaskHookProvider.
type MockITaskHookProviderMockRecorder struct {
	mock *MockITaskHookProvider
}

// NewMockITaskHookProvider creates a new mock instance.
func NewMockITaskHookProvider(ctrl *gomock.Controller) *MockITaskHookProvider {
	mock := &MockITaskHookProvider{ctrl: ctrl}
	mock.recorder = &MockITaskHookProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskHookProvider) EXPECT() *MockITaskHookProviderMockRecorder {
	return m.recorder
}

// OnTaskFinished mocks base method.
func (m *MockITaskHookProvider) WorkflowCallback(ctx context.Context, event *task.WorkflowCallbackParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkflowCallback", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnTaskFinished indicates an expected call of OnTaskFinished.
func (mr *MockITaskHookProviderMockRecorder) OnTaskFinished(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkflowCallback", reflect.TypeOf((*MockITaskHookProvider)(nil).WorkflowCallback), ctx, event)
}
