// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package observability

import (
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability/ingestion"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability/openapi"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability/task"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability/trace"
)

type ObservabilityTraceService interface {
	trace.TraceService
}

type ObservabilityTraceServiceClient struct {
	*trace.TraceServiceClient
}

func NewObservabilityTraceServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ObservabilityTraceServiceClient {
	return &ObservabilityTraceServiceClient{
		TraceServiceClient: trace.NewTraceServiceClientFactory(t, f),
	}
}

func NewObservabilityTraceServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ObservabilityTraceServiceClient {
	return &ObservabilityTraceServiceClient{
		TraceServiceClient: trace.NewTraceServiceClientProtocol(t, iprot, oprot),
	}
}

func NewObservabilityTraceServiceClient(c thrift.TClient) *ObservabilityTraceServiceClient {
	return &ObservabilityTraceServiceClient{
		TraceServiceClient: trace.NewTraceServiceClient(c),
	}
}

type ObservabilityOpenAPIService interface {
	openapi.OpenAPIService
}

type ObservabilityOpenAPIServiceClient struct {
	*openapi.OpenAPIServiceClient
}

func NewObservabilityOpenAPIServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ObservabilityOpenAPIServiceClient {
	return &ObservabilityOpenAPIServiceClient{
		OpenAPIServiceClient: openapi.NewOpenAPIServiceClientFactory(t, f),
	}
}

func NewObservabilityOpenAPIServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ObservabilityOpenAPIServiceClient {
	return &ObservabilityOpenAPIServiceClient{
		OpenAPIServiceClient: openapi.NewOpenAPIServiceClientProtocol(t, iprot, oprot),
	}
}

func NewObservabilityOpenAPIServiceClient(c thrift.TClient) *ObservabilityOpenAPIServiceClient {
	return &ObservabilityOpenAPIServiceClient{
		OpenAPIServiceClient: openapi.NewOpenAPIServiceClient(c),
	}
}

type ObservabilityTaskService interface {
	task.TaskService
}

type ObservabilityTaskServiceClient struct {
	*task.TaskServiceClient
}

func NewObservabilityTaskServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ObservabilityTaskServiceClient {
	return &ObservabilityTaskServiceClient{
		TaskServiceClient: task.NewTaskServiceClientFactory(t, f),
	}
}

func NewObservabilityTaskServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ObservabilityTaskServiceClient {
	return &ObservabilityTaskServiceClient{
		TaskServiceClient: task.NewTaskServiceClientProtocol(t, iprot, oprot),
	}
}

func NewObservabilityTaskServiceClient(c thrift.TClient) *ObservabilityTaskServiceClient {
	return &ObservabilityTaskServiceClient{
		TaskServiceClient: task.NewTaskServiceClient(c),
	}
}

type IngestionService interface {
	ingestion.IngestionService
}

type IngestionServiceClient struct {
	*ingestion.IngestionServiceClient
}

func NewIngestionServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *IngestionServiceClient {
	return &IngestionServiceClient{
		IngestionServiceClient: ingestion.NewIngestionServiceClientFactory(t, f),
	}
}

func NewIngestionServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *IngestionServiceClient {
	return &IngestionServiceClient{
		IngestionServiceClient: ingestion.NewIngestionServiceClientProtocol(t, iprot, oprot),
	}
}

func NewIngestionServiceClient(c thrift.TClient) *IngestionServiceClient {
	return &IngestionServiceClient{
		IngestionServiceClient: ingestion.NewIngestionServiceClient(c),
	}
}

type ObservabilityTraceServiceProcessor struct {
	*trace.TraceServiceProcessor
}

func NewObservabilityTraceServiceProcessor(handler ObservabilityTraceService) *ObservabilityTraceServiceProcessor {
	self := &ObservabilityTraceServiceProcessor{trace.NewTraceServiceProcessor(handler)}
	return self
}

type ObservabilityOpenAPIServiceProcessor struct {
	*openapi.OpenAPIServiceProcessor
}

func NewObservabilityOpenAPIServiceProcessor(handler ObservabilityOpenAPIService) *ObservabilityOpenAPIServiceProcessor {
	self := &ObservabilityOpenAPIServiceProcessor{openapi.NewOpenAPIServiceProcessor(handler)}
	return self
}

type ObservabilityTaskServiceProcessor struct {
	*task.TaskServiceProcessor
}

func NewObservabilityTaskServiceProcessor(handler ObservabilityTaskService) *ObservabilityTaskServiceProcessor {
	self := &ObservabilityTaskServiceProcessor{task.NewTaskServiceProcessor(handler)}
	return self
}

type IngestionServiceProcessor struct {
	*ingestion.IngestionServiceProcessor
}

func NewIngestionServiceProcessor(handler IngestionService) *IngestionServiceProcessor {
	self := &IngestionServiceProcessor{ingestion.NewIngestionServiceProcessor(handler)}
	return self
}
