CREATE TABLE IF NOT EXISTS `expt_lifecycle_run`
(
    `space_id` bigint unsigned NOT NULL,
    `expt_id` bigint NOT NULL,
    `expt_run_id` bigint unsigned NOT NULL,
    `source_run_id` bigint DEFAULT NULL,
    `before_enabled` bool NOT NULL DEFAULT false COMMENT '创建时冻结的before启用状态',
    `after_enabled` bool NOT NULL DEFAULT false COMMENT '创建时冻结的after启用状态',
    `execution_scope` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `snapshot_cipher` mediumblob DEFAULT NULL,
    `snapshot_key_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `snapshot_hash` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `gate` tinyint NOT NULL DEFAULT '0' COMMENT '0 waiting, 1 ready, 2 closed',
    `plan_state` tinyint NOT NULL DEFAULT '0' COMMENT '0 preparing, 1 ready',
    `plan_cursor` text DEFAULT NULL,
    `plan_count` bigint NOT NULL DEFAULT '0',
    `plan_hash` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
    `execution_started` bool NOT NULL DEFAULT false,
    `execution_initialized` bool NOT NULL DEFAULT false,
    `version` bigint unsigned NOT NULL DEFAULT '0',
    `terminal_status` smallint DEFAULT NULL,
    `terminal_reason` varchar(128) DEFAULT NULL,
    `terminal_at` datetime(3) DEFAULT NULL,
    `finalize_state` tinyint NOT NULL DEFAULT '0' COMMENT '0 none, 1 pending, 2 committed',
    `next_reconcile_at` datetime(3) DEFAULT NULL,
    `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`space_id`, `expt_run_id`),
    UNIQUE KEY `uk_expt_run` (`expt_id`, `expt_run_id`),
    KEY `idx_scope_finalize_reconcile` (`execution_scope`, `finalize_state`, `next_reconcile_at`),
    KEY `idx_scope_plan_run` (`execution_scope`, `plan_state`, `space_id`, `expt_run_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;
