# Prometheus 配置文件
# 用于监控 coze-loop Python FaaS 服务

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'coze-loop-prod'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Python FaaS 监控
  - job_name: 'python-faas'
    static_configs:
      - targets: ['coze-loop-python-faas-prod:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: coze-loop-python-faas-prod:8000
      - target_label: service
        replacement: python-faas
      - target_label: environment
        replacement: production

  # JavaScript FaaS 监控
  - job_name: 'js-faas'
    static_configs:
      - targets: ['coze-loop-js-faas-prod:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: js-faas
      - target_label: environment
        replacement: production

  # 应用服务监控
  - job_name: 'coze-loop-app'
    static_configs:
      - targets: ['app:8888']
    metrics_path: '/metrics'
    scrape_interval: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: coze-loop-app
      - target_label: environment
        replacement: production

  # Redis 监控 (如果启用了 redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: redis
      - target_label: environment
        replacement: production

  # MySQL 监控 (如果启用了 mysqld_exporter)
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: mysql
      - target_label: environment
        replacement: production

  # ClickHouse 监控
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: '/metrics'
    scrape_interval: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: clickhouse
      - target_label: environment
        replacement: production

  # MinIO 监控
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: minio
      - target_label: environment
        replacement: production

  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: prometheus
      - target_label: environment
        replacement: production

  # 节点监控 (如果启用了 node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: node-exporter
      - target_label: environment
        replacement: production

  # cAdvisor 容器监控 (如果启用)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    honor_labels: true
    relabel_configs:
      - target_label: service
        replacement: cadvisor
      - target_label: environment
        replacement: production