CREATE TABLE IF NOT EXISTS `expt_lifecycle_hook_run`
(
    `id` bigint unsigned NOT NULL,
    `space_id` bigint NOT NULL,
    `expt_id` bigint NOT NULL,
    `expt_run_id` bigint NOT NULL,
    `phase` varchar(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `operation_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `idempotency_key` varchar(256) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `activated_at` datetime(3) DEFAULT NULL,
    `attempt` int NOT NULL DEFAULT '0',
    `next_attempt_at` datetime(3) DEFAULT NULL,
    `operation_deadline` datetime(3) DEFAULT NULL,
    `attempt_deadline` datetime(3) DEFAULT NULL,
    `lease_until` datetime(3) DEFAULT NULL,
    `lease_owner` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
    `lease_generation` bigint unsigned NOT NULL DEFAULT '0',
    `version` bigint unsigned NOT NULL DEFAULT '0',
    `occurred_at` datetime(3) DEFAULT NULL,
    `request_hash` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
    `result_redacted` blob DEFAULT NULL,
    `error_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
    `error_message` varchar(2048) DEFAULT NULL,
    `execution_scope` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_run_phase` (`space_id`, `expt_run_id`, `phase`),
    UNIQUE KEY `uk_operation_id` (`operation_id`),
    UNIQUE KEY `uk_idempotency_key` (`idempotency_key`),
    KEY `idx_scope_status_next` (`execution_scope`, `status`, `next_attempt_at`, `id`),
    KEY `idx_scope_status_lease` (`execution_scope`, `status`, `lease_until`, `id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;
