custom: &custom
  image:
    registry: "docker.io"
    pullSecrets: "***"
  redis:
    disabled: true
  mysql:
    disabled: true
  clickhouse:
    disabled: true
  oss:
    disabled: true
  rmq:
    disabled: true

# 固定，不要动，用于传递全局变量
coze-loop-app:
  # 合并全局 custom，并仅覆盖 app 的 registry 为空
  custom:
    <<: *custom
    image:
      registry: ""
  image:
    pullSecrets: ""
    pullPolicy: Never
coze-loop-nginx:
  custom: *custom
coze-loop-redis:
  custom: *custom
coze-loop-mysql:
  custom: *custom
coze-loop-clickhouse:
  custom: *custom
coze-loop-minio:
  custom: *custom
coze-loop-rmq-namesrv:
  custom: *custom
coze-loop-rmq-broker:
  custom: *custom
coze-loop-python-faas:
  custom: *custom
coze-loop-js-faas:
  custom: *custom
