// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameObservabilityTaskRun = "auto_task_run"

// ObservabilityTaskRun mapped from table <auto_task_run>
type ObservabilityTaskRun struct {
}

// TableName ObservabilityTaskRun's table name
func (*ObservabilityTaskRun) TableName() string {
	return TableNameObservabilityTaskRun
}
