// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameObservabilityTask = "task"

// ObservabilityTask mapped from table <task>
type ObservabilityTask struct {
}

// TableName ObservabilityTask's table name
func (*ObservabilityTask) TableName() string {
	return TableNameObservabilityTask
}
