// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package ingestion

import (
	"context"
	"github.com/apache/thrift/lib/go/thrift"
)

type IngestionService interface {
}

type IngestionServiceClient struct {
	c thrift.TClient
}

func NewIngestionServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *IngestionServiceClient {
	return &IngestionServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewIngestionServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *IngestionServiceClient {
	return &IngestionServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewIngestionServiceClient(c thrift.TClient) *IngestionServiceClient {
	return &IngestionServiceClient{
		c: c,
	}
}

func (p *IngestionServiceClient) Client_() thrift.TClient {
	return p.c
}

type IngestionServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      IngestionService
}

func (p *IngestionServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *IngestionServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *IngestionServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewIngestionServiceProcessor(handler IngestionService) *IngestionServiceProcessor {
	self := &IngestionServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	return self
}
func (p *IngestionServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}
