name: CI@frontend - Main

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yaml'
  pull_request:
    branches: ["main"]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yaml'
  workflow_dispatch:

jobs:
  setup:
    name: Build All
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '18'
      # should be ci trigger user
      GIT_USER_NAME: 'mocayo'
      GIT_USER_EMAIL: 'qihai@bytedance.com'
      BUILD_BRANCH: ${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Config Git User
        run: |
          git config --local user.name ${{ env.GIT_USER_NAME }}
          git config --local user.email ${{ env.GIT_USER_EMAIL }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            common/temp/pnpm-local
            common/temp/pnpm-store
            common/temp/install-run
          key: ${{ runner.os }}-rush-store-${{ hashFiles('common/config/subspaces/default/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-rush-store-main
            ${{ runner.os }}-rush-store

      - name: Branch Diff
        id: branch-diff
        run: |
          TARGET_BRANCH="${GITHUB_BASE_REF:-main}"
          git fetch origin $TARGET_BRANCH
          sh .github/scripts/branch-diff.sh origin/$TARGET_BRANCH > changed.json
          echo "file=changed.json" >> "$GITHUB_OUTPUT"

      - name: Install Dependencies
        run: |
          node common/scripts/install-run-rush.js install

      - name: Build All
        run: |
          node common/scripts/install-run-rush.js rebuild --verbose --timeline

      - name: Lint & Style
        run: |
          node common/scripts/install-run-rush.js increment --action lint -p ${{ steps.branch-diff.outputs.file }}
          node common/scripts/install-run-rush.js increment --action style -p ${{ steps.branch-diff.outputs.file }}
